// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System.Collections.Generic;

	public static class Archetypes
	{
		public const int Character_ef7ce5f54c7d78b479854b7248d15c5aIndex = 0;
		public const int Classic__char_32_Tongue_4a710caa256322a4aa6bfb19109e4559Index = 1;
		public const int Map_47cb5312f9d22b34095ab0d72bfecbcdIndex = 2;

		public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() {
			{ "Character_ef7ce5f54c7d78b479854b7248d15c5a", 0 },

			{ "Classic__char_32_Tongue_4a710caa256322a4aa6bfb19109e4559", 1 },

			{ "Map_47cb5312f9d22b34095ab0d72bfecbcd", 2 },

		};
	}
}
