// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.SimulationFrame;
	using Coherence.Entity;
	using Coherence.Utils;
	using Coherence.Brook;
	using Coherence.Toolkit;
	using UnityEngine;

	public struct Character_UnityEngine__char_46_Animator_4441217298144173237 : ICoherenceComponentData
	{
		public int character;
		public float Speed;

		public override string ToString()
		{
			return $"Character_UnityEngine__char_46_Animator_4441217298144173237(character: {character}, Speed: {Speed})";
		}

		public uint GetComponentType() => Definition.InternalCharacter_UnityEngine__char_46_Animator_4441217298144173237;

		public const int order = 0;

		public int GetComponentOrder() => order;

		public AbsoluteSimulationFrame Frame;
	
		private static readonly int _character_Min = -2147483648;
		private static readonly int _character_Max = 2147483647;

		public void SetSimulationFrame(AbsoluteSimulationFrame frame)
		{
			Frame = frame;
		}

		public AbsoluteSimulationFrame GetSimulationFrame() => Frame;

		public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
		{
			var other = (Character_UnityEngine__char_46_Animator_4441217298144173237)data;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				character = other.character;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				Speed = other.Speed;
			}
			mask >>= 1;
			return this;
		}

		public uint DiffWith(ICoherenceComponentData data)
		{
			throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");

		}

		public static void Serialize(Character_UnityEngine__char_46_Animator_4441217298144173237 data, uint mask, IOutProtocolBitStream bitStream)
		{
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				Coherence.Utils.Bounds.Check(data.character, _character_Min, _character_Max, "Character_UnityEngine__char_46_Animator_4441217298144173237.character");
				data.character = Coherence.Utils.Bounds.Clamp(data.character, _character_Min, _character_Max);
				bitStream.WriteIntegerRange(data.character, 32, -2147483648);
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteFloat(data.Speed, FloatMeta.NoCompression());
			}
			mask >>= 1;
		}

		public static (Character_UnityEngine__char_46_Animator_4441217298144173237, uint, uint?) Deserialize(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new Character_UnityEngine__char_46_Animator_4441217298144173237();
	
			if (bitStream.ReadMask())
			{
				val.character = bitStream.ReadIntegerRange(32, -2147483648);
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.Speed = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000010;
			}
			return (val, mask, null);
		}
		public static (Character_UnityEngine__char_46_Animator_4441217298144173237, uint, uint?) DeserializeArchetypeCharacter_ef7ce5f54c7d78b479854b7248d15c5a_Character_UnityEngine__char_46_Animator_4441217298144173237_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new Character_UnityEngine__char_46_Animator_4441217298144173237();
			if (bitStream.ReadMask())
			{
				val.character = bitStream.ReadIntegerRange(32, -2147483648);
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.Speed = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000010;
			}

			return (val, mask, 0);
		}

		/// <summary>
		/// Resets byte array references to the local array instance that is kept in the lastSentData.
		/// If the array content has changed but remains of same length, the new content is copied into the local array instance.
		/// If the array length has changed, the array is cloned and overwrites the local instance.
		/// If the array has not changed, the reference is reset to the local array instance.
		/// Otherwise, changes to other fields on the component might cause the local array instance reference to become permanently lost.
		/// </summary>
		public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
		{
			var last = lastSent as Character_UnityEngine__char_46_Animator_4441217298144173237?;
	
		}
	}
}