// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.SimulationFrame;
	using Coherence.Entity;
	using Coherence.Utils;
	using Coherence.Brook;
	using Coherence.Toolkit;
	using UnityEngine;

	public struct Character_FrogCharacterController_4441217298144173242 : ICoherenceComponentData
	{
		public SerializeEntityID weaponStartPoint;
		public float attackCooldownBoost;
		public float attackRangeBoost;
		public float attackSizeBoost;
		public float attackSpeedBoost;
		public float attackDurationBoost;
		public float attackSpecialStrengthBoost;
		public float attackSpecialDurationBoost;

		public override string ToString()
		{
			return $"Character_FrogCharacterController_4441217298144173242(weaponStartPoint: {weaponStartPoint}, attackCooldownBoost: {attackCooldownBoost}, attackRangeBoost: {attackRangeBoost}, attackSizeBoost: {attackSizeBoost}, attackSpeedBoost: {attackSpeedBoost}, attackDurationBoost: {attackDurationBoost}, attackSpecialStrengthBoost: {attackSpecialStrengthBoost}, attackSpecialDurationBoost: {attackSpecialDurationBoost})";
		}

		public uint GetComponentType() => Definition.InternalCharacter_FrogCharacterController_4441217298144173242;

		public const int order = 0;

		public int GetComponentOrder() => order;

		public AbsoluteSimulationFrame Frame;
	

		public void SetSimulationFrame(AbsoluteSimulationFrame frame)
		{
			Frame = frame;
		}

		public AbsoluteSimulationFrame GetSimulationFrame() => Frame;

		public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
		{
			var other = (Character_FrogCharacterController_4441217298144173242)data;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				weaponStartPoint = other.weaponStartPoint;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				attackCooldownBoost = other.attackCooldownBoost;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				attackRangeBoost = other.attackRangeBoost;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				attackSizeBoost = other.attackSizeBoost;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				attackSpeedBoost = other.attackSpeedBoost;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				attackDurationBoost = other.attackDurationBoost;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				attackSpecialStrengthBoost = other.attackSpecialStrengthBoost;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				attackSpecialDurationBoost = other.attackSpecialDurationBoost;
			}
			mask >>= 1;
			return this;
		}

		public uint DiffWith(ICoherenceComponentData data)
		{
			throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");

		}

		public static void Serialize(Character_FrogCharacterController_4441217298144173242 data, uint mask, IOutProtocolBitStream bitStream)
		{
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteEntity(data.weaponStartPoint);
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteFloat(data.attackCooldownBoost, FloatMeta.NoCompression());
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteFloat(data.attackRangeBoost, FloatMeta.NoCompression());
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteFloat(data.attackSizeBoost, FloatMeta.NoCompression());
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteFloat(data.attackSpeedBoost, FloatMeta.NoCompression());
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteFloat(data.attackDurationBoost, FloatMeta.NoCompression());
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteFloat(data.attackSpecialStrengthBoost, FloatMeta.NoCompression());
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteFloat(data.attackSpecialDurationBoost, FloatMeta.NoCompression());
			}
			mask >>= 1;
		}

		public static (Character_FrogCharacterController_4441217298144173242, uint, uint?) Deserialize(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new Character_FrogCharacterController_4441217298144173242();
	
			if (bitStream.ReadMask())
			{
				val.weaponStartPoint = bitStream.ReadEntity();
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.attackCooldownBoost = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000010;
			}
			if (bitStream.ReadMask())
			{
				val.attackRangeBoost = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000100;
			}
			if (bitStream.ReadMask())
			{
				val.attackSizeBoost = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000001000;
			}
			if (bitStream.ReadMask())
			{
				val.attackSpeedBoost = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000010000;
			}
			if (bitStream.ReadMask())
			{
				val.attackDurationBoost = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000100000;
			}
			if (bitStream.ReadMask())
			{
				val.attackSpecialStrengthBoost = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000001000000;
			}
			if (bitStream.ReadMask())
			{
				val.attackSpecialDurationBoost = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000010000000;
			}
			return (val, mask, null);
		}
		public static (Character_FrogCharacterController_4441217298144173242, uint, uint?) DeserializeArchetypeCharacter_ef7ce5f54c7d78b479854b7248d15c5a_Character_FrogCharacterController_4441217298144173242_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new Character_FrogCharacterController_4441217298144173242();
			if (bitStream.ReadMask())
			{
				val.weaponStartPoint = bitStream.ReadEntity();
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.attackCooldownBoost = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000010;
			}
			if (bitStream.ReadMask())
			{
				val.attackRangeBoost = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000100;
			}
			if (bitStream.ReadMask())
			{
				val.attackSizeBoost = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000001000;
			}
			if (bitStream.ReadMask())
			{
				val.attackSpeedBoost = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000010000;
			}
			if (bitStream.ReadMask())
			{
				val.attackDurationBoost = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000100000;
			}
			if (bitStream.ReadMask())
			{
				val.attackSpecialStrengthBoost = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000001000000;
			}
			if (bitStream.ReadMask())
			{
				val.attackSpecialDurationBoost = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000010000000;
			}

			return (val, mask, 0);
		}
		public static (Character_FrogCharacterController_4441217298144173242, uint, uint?) DeserializeArchetypeCharacter_ef7ce5f54c7d78b479854b7248d15c5a_Character_FrogCharacterController_4441217298144173242_LOD1(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new Character_FrogCharacterController_4441217298144173242();
			if (bitStream.ReadMask())
			{
				val.weaponStartPoint = bitStream.ReadEntity();
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.attackCooldownBoost = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000010;
			}
			if (bitStream.ReadMask())
			{
				val.attackRangeBoost = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000100;
			}
			if (bitStream.ReadMask())
			{
				val.attackSizeBoost = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000001000;
			}
			if (bitStream.ReadMask())
			{
				val.attackSpeedBoost = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000010000;
			}
			if (bitStream.ReadMask())
			{
				val.attackDurationBoost = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000100000;
			}
			if (bitStream.ReadMask())
			{
				val.attackSpecialStrengthBoost = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000001000000;
			}
			if (bitStream.ReadMask())
			{
				val.attackSpecialDurationBoost = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000010000000;
			}

			return (val, mask, 1);
		}
		public static (Character_FrogCharacterController_4441217298144173242, uint, uint?) DeserializeArchetypeCharacter_ef7ce5f54c7d78b479854b7248d15c5a_Character_FrogCharacterController_4441217298144173242_LOD2(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new Character_FrogCharacterController_4441217298144173242();
			if (bitStream.ReadMask())
			{
				val.weaponStartPoint = bitStream.ReadEntity();
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.attackCooldownBoost = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000010;
			}
			if (bitStream.ReadMask())
			{
				val.attackRangeBoost = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000100;
			}
			if (bitStream.ReadMask())
			{
				val.attackSizeBoost = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000001000;
			}
			if (bitStream.ReadMask())
			{
				val.attackSpeedBoost = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000010000;
			}
			if (bitStream.ReadMask())
			{
				val.attackDurationBoost = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000100000;
			}
			if (bitStream.ReadMask())
			{
				val.attackSpecialStrengthBoost = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000001000000;
			}
			if (bitStream.ReadMask())
			{
				val.attackSpecialDurationBoost = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000010000000;
			}

			return (val, mask, 2);
		}

		/// <summary>
		/// Resets byte array references to the local array instance that is kept in the lastSentData.
		/// If the array content has changed but remains of same length, the new content is copied into the local array instance.
		/// If the array length has changed, the array is cloned and overwrites the local instance.
		/// If the array has not changed, the reference is reset to the local array instance.
		/// Otherwise, changes to other fields on the component might cause the local array instance reference to become permanently lost.
		/// </summary>
		public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
		{
			var last = lastSent as Character_FrogCharacterController_4441217298144173242?;
	
		}
	}
}