// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.SimulationFrame;
	using Coherence.Entity;
	using Coherence.Utils;
	using Coherence.Brook;
	using Coherence.Toolkit;
	using UnityEngine;

	public struct Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178 : ICoherenceComponentData
	{
		public float tongueWidth;
		public Color outlineColor;
		public float outlineWeight;
		public float cooldown;
		public float attackSpeed;
		public float range;
		public float duration;
		public float knockbackForce;
		public float damage;
		public float healthAbsorbRatio;
		public float poisonDamage;
		public bool freezeEffect;
		public float curseChance;
		public float lastAttackTime;
		public bool isAttacking;
		public bool preventAttack;
		public int tongueTypeIndex;
		public int tongueTypeCount;
		public bool enabled;

		public override string ToString()
		{
			return $"Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178(tongueWidth: {tongueWidth}, outlineColor: {outlineColor}, outlineWeight: {outlineWeight}, cooldown: {cooldown}, attackSpeed: {attackSpeed}, range: {range}, duration: {duration}, knockbackForce: {knockbackForce}, damage: {damage}, healthAbsorbRatio: {healthAbsorbRatio}, poisonDamage: {poisonDamage}, freezeEffect: {freezeEffect}, curseChance: {curseChance}, lastAttackTime: {lastAttackTime}, isAttacking: {isAttacking}, preventAttack: {preventAttack}, tongueTypeIndex: {tongueTypeIndex}, tongueTypeCount: {tongueTypeCount}, enabled: {enabled})";
		}

		public uint GetComponentType() => Definition.InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178;

		public const int order = 0;

		public int GetComponentOrder() => order;

		public AbsoluteSimulationFrame Frame;
	
		private static readonly int _tongueTypeIndex_Min = -2147483648;
		private static readonly int _tongueTypeIndex_Max = 2147483647;
		private static readonly int _tongueTypeCount_Min = -2147483648;
		private static readonly int _tongueTypeCount_Max = 2147483647;

		public void SetSimulationFrame(AbsoluteSimulationFrame frame)
		{
			Frame = frame;
		}

		public AbsoluteSimulationFrame GetSimulationFrame() => Frame;

		public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
		{
			var other = (Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)data;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				tongueWidth = other.tongueWidth;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				outlineColor = other.outlineColor;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				outlineWeight = other.outlineWeight;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				cooldown = other.cooldown;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				attackSpeed = other.attackSpeed;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				range = other.range;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				duration = other.duration;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				knockbackForce = other.knockbackForce;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				damage = other.damage;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				healthAbsorbRatio = other.healthAbsorbRatio;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				poisonDamage = other.poisonDamage;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				freezeEffect = other.freezeEffect;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				curseChance = other.curseChance;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				lastAttackTime = other.lastAttackTime;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				isAttacking = other.isAttacking;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				preventAttack = other.preventAttack;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				tongueTypeIndex = other.tongueTypeIndex;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				tongueTypeCount = other.tongueTypeCount;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				enabled = other.enabled;
			}
			mask >>= 1;
			return this;
		}

		public uint DiffWith(ICoherenceComponentData data)
		{
			throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");

		}

		public static void Serialize(Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178 data, uint mask, IOutProtocolBitStream bitStream)
		{
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteFloat(data.tongueWidth, FloatMeta.NoCompression());
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteColor((data.outlineColor.ToCoreColor()), FloatMeta.ForFixedPoint(0, 1, 2.3283064370807973753052522170037E-10));
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteFloat(data.outlineWeight, FloatMeta.NoCompression());
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteFloat(data.cooldown, FloatMeta.NoCompression());
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteFloat(data.attackSpeed, FloatMeta.NoCompression());
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteFloat(data.range, FloatMeta.NoCompression());
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteFloat(data.duration, FloatMeta.NoCompression());
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteFloat(data.knockbackForce, FloatMeta.NoCompression());
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteFloat(data.damage, FloatMeta.NoCompression());
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteFloat(data.healthAbsorbRatio, FloatMeta.NoCompression());
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteFloat(data.poisonDamage, FloatMeta.NoCompression());
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteBool(data.freezeEffect);
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteFloat(data.curseChance, FloatMeta.NoCompression());
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteFloat(data.lastAttackTime, FloatMeta.NoCompression());
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteBool(data.isAttacking);
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteBool(data.preventAttack);
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				Coherence.Utils.Bounds.Check(data.tongueTypeIndex, _tongueTypeIndex_Min, _tongueTypeIndex_Max, "Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178.tongueTypeIndex");
				data.tongueTypeIndex = Coherence.Utils.Bounds.Clamp(data.tongueTypeIndex, _tongueTypeIndex_Min, _tongueTypeIndex_Max);
				bitStream.WriteIntegerRange(data.tongueTypeIndex, 32, -2147483648);
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				Coherence.Utils.Bounds.Check(data.tongueTypeCount, _tongueTypeCount_Min, _tongueTypeCount_Max, "Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178.tongueTypeCount");
				data.tongueTypeCount = Coherence.Utils.Bounds.Clamp(data.tongueTypeCount, _tongueTypeCount_Min, _tongueTypeCount_Max);
				bitStream.WriteIntegerRange(data.tongueTypeCount, 32, -2147483648);
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteBool(data.enabled);
			}
			mask >>= 1;
		}

		public static (Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178, uint, uint?) Deserialize(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178();
	
			if (bitStream.ReadMask())
			{
				val.tongueWidth = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.outlineColor = (bitStream.ReadColor(FloatMeta.ForFixedPoint(0, 1, 2.3283064370807973753052522170037E-10))).ToUnityColor();
				mask |= 0b00000000000000000000000000000010;
			}
			if (bitStream.ReadMask())
			{
				val.outlineWeight = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000100;
			}
			if (bitStream.ReadMask())
			{
				val.cooldown = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000001000;
			}
			if (bitStream.ReadMask())
			{
				val.attackSpeed = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000010000;
			}
			if (bitStream.ReadMask())
			{
				val.range = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000100000;
			}
			if (bitStream.ReadMask())
			{
				val.duration = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000001000000;
			}
			if (bitStream.ReadMask())
			{
				val.knockbackForce = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000010000000;
			}
			if (bitStream.ReadMask())
			{
				val.damage = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000100000000;
			}
			if (bitStream.ReadMask())
			{
				val.healthAbsorbRatio = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000001000000000;
			}
			if (bitStream.ReadMask())
			{
				val.poisonDamage = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000010000000000;
			}
			if (bitStream.ReadMask())
			{
				val.freezeEffect = bitStream.ReadBool();
				mask |= 0b00000000000000000000100000000000;
			}
			if (bitStream.ReadMask())
			{
				val.curseChance = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000001000000000000;
			}
			if (bitStream.ReadMask())
			{
				val.lastAttackTime = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000010000000000000;
			}
			if (bitStream.ReadMask())
			{
				val.isAttacking = bitStream.ReadBool();
				mask |= 0b00000000000000000100000000000000;
			}
			if (bitStream.ReadMask())
			{
				val.preventAttack = bitStream.ReadBool();
				mask |= 0b00000000000000001000000000000000;
			}
			if (bitStream.ReadMask())
			{
				val.tongueTypeIndex = bitStream.ReadIntegerRange(32, -2147483648);
				mask |= 0b00000000000000010000000000000000;
			}
			if (bitStream.ReadMask())
			{
				val.tongueTypeCount = bitStream.ReadIntegerRange(32, -2147483648);
				mask |= 0b00000000000000100000000000000000;
			}
			if (bitStream.ReadMask())
			{
				val.enabled = bitStream.ReadBool();
				mask |= 0b00000000000001000000000000000000;
			}
			return (val, mask, null);
		}
		public static (Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178, uint, uint?) DeserializeArchetypeClassic__char_32_Tongue_4a710caa256322a4aa6bfb19109e4559_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178();
			if (bitStream.ReadMask())
			{
				val.tongueWidth = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.outlineColor = (bitStream.ReadColor(FloatMeta.ForFixedPoint(0, 1, 2.3283064370807973753052522170037E-10))).ToUnityColor();
				mask |= 0b00000000000000000000000000000010;
			}
			if (bitStream.ReadMask())
			{
				val.outlineWeight = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000100;
			}
			if (bitStream.ReadMask())
			{
				val.cooldown = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000001000;
			}
			if (bitStream.ReadMask())
			{
				val.attackSpeed = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000010000;
			}
			if (bitStream.ReadMask())
			{
				val.range = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000100000;
			}
			if (bitStream.ReadMask())
			{
				val.duration = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000001000000;
			}
			if (bitStream.ReadMask())
			{
				val.knockbackForce = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000010000000;
			}
			if (bitStream.ReadMask())
			{
				val.damage = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000100000000;
			}
			if (bitStream.ReadMask())
			{
				val.healthAbsorbRatio = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000001000000000;
			}
			if (bitStream.ReadMask())
			{
				val.poisonDamage = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000010000000000;
			}
			if (bitStream.ReadMask())
			{
				val.freezeEffect = bitStream.ReadBool();
				mask |= 0b00000000000000000000100000000000;
			}
			if (bitStream.ReadMask())
			{
				val.curseChance = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000001000000000000;
			}
			if (bitStream.ReadMask())
			{
				val.lastAttackTime = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000010000000000000;
			}
			if (bitStream.ReadMask())
			{
				val.isAttacking = bitStream.ReadBool();
				mask |= 0b00000000000000000100000000000000;
			}
			if (bitStream.ReadMask())
			{
				val.preventAttack = bitStream.ReadBool();
				mask |= 0b00000000000000001000000000000000;
			}
			if (bitStream.ReadMask())
			{
				val.tongueTypeIndex = bitStream.ReadIntegerRange(32, -2147483648);
				mask |= 0b00000000000000010000000000000000;
			}
			if (bitStream.ReadMask())
			{
				val.tongueTypeCount = bitStream.ReadIntegerRange(32, -2147483648);
				mask |= 0b00000000000000100000000000000000;
			}
			if (bitStream.ReadMask())
			{
				val.enabled = bitStream.ReadBool();
				mask |= 0b00000000000001000000000000000000;
			}

			return (val, mask, 0);
		}

		/// <summary>
		/// Resets byte array references to the local array instance that is kept in the lastSentData.
		/// If the array content has changed but remains of same length, the new content is copied into the local array instance.
		/// If the array length has changed, the array is cloned and overwrites the local instance.
		/// If the array has not changed, the reference is reset to the local array instance.
		/// Otherwise, changes to other fields on the component might cause the local array instance reference to become permanently lost.
		/// </summary>
		public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
		{
			var last = lastSent as Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178?;
	
		}
	}
}