// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.SimulationFrame;
	using Coherence.Entity;
	using Coherence.Utils;
	using Coherence.Brook;
	using Coherence.Toolkit;
	using UnityEngine;

	public struct Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180 : ICoherenceComponentData
	{
		public float startWidth;
		public float endWidth;
		public float widthMultiplier;
		public Color startColor;
		public Color endColor;
		public bool enabled;
		public int sortingOrder;

		public override string ToString()
		{
			return $"Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180(startWidth: {startWidth}, endWidth: {endWidth}, widthMultiplier: {widthMultiplier}, startColor: {startColor}, endColor: {endColor}, enabled: {enabled}, sortingOrder: {sortingOrder})";
		}

		public uint GetComponentType() => Definition.InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180;

		public const int order = 0;

		public int GetComponentOrder() => order;

		public AbsoluteSimulationFrame Frame;
	
		private static readonly int _sortingOrder_Min = -2147483648;
		private static readonly int _sortingOrder_Max = 2147483647;

		public void SetSimulationFrame(AbsoluteSimulationFrame frame)
		{
			Frame = frame;
		}

		public AbsoluteSimulationFrame GetSimulationFrame() => Frame;

		public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
		{
			var other = (Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180)data;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				startWidth = other.startWidth;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				endWidth = other.endWidth;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				widthMultiplier = other.widthMultiplier;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				startColor = other.startColor;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				endColor = other.endColor;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				enabled = other.enabled;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				sortingOrder = other.sortingOrder;
			}
			mask >>= 1;
			return this;
		}

		public uint DiffWith(ICoherenceComponentData data)
		{
			throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");

		}

		public static void Serialize(Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180 data, uint mask, IOutProtocolBitStream bitStream)
		{
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteFloat(data.startWidth, FloatMeta.NoCompression());
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteFloat(data.endWidth, FloatMeta.NoCompression());
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteFloat(data.widthMultiplier, FloatMeta.NoCompression());
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteColor((data.startColor.ToCoreColor()), FloatMeta.ForFixedPoint(0, 1, 2.3283064370807973753052522170037E-10));
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteColor((data.endColor.ToCoreColor()), FloatMeta.ForFixedPoint(0, 1, 2.3283064370807973753052522170037E-10));
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteBool(data.enabled);
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				Coherence.Utils.Bounds.Check(data.sortingOrder, _sortingOrder_Min, _sortingOrder_Max, "Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180.sortingOrder");
				data.sortingOrder = Coherence.Utils.Bounds.Clamp(data.sortingOrder, _sortingOrder_Min, _sortingOrder_Max);
				bitStream.WriteIntegerRange(data.sortingOrder, 32, -2147483648);
			}
			mask >>= 1;
		}

		public static (Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180, uint, uint?) Deserialize(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180();
	
			if (bitStream.ReadMask())
			{
				val.startWidth = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.endWidth = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000010;
			}
			if (bitStream.ReadMask())
			{
				val.widthMultiplier = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000100;
			}
			if (bitStream.ReadMask())
			{
				val.startColor = (bitStream.ReadColor(FloatMeta.ForFixedPoint(0, 1, 2.3283064370807973753052522170037E-10))).ToUnityColor();
				mask |= 0b00000000000000000000000000001000;
			}
			if (bitStream.ReadMask())
			{
				val.endColor = (bitStream.ReadColor(FloatMeta.ForFixedPoint(0, 1, 2.3283064370807973753052522170037E-10))).ToUnityColor();
				mask |= 0b00000000000000000000000000010000;
			}
			if (bitStream.ReadMask())
			{
				val.enabled = bitStream.ReadBool();
				mask |= 0b00000000000000000000000000100000;
			}
			if (bitStream.ReadMask())
			{
				val.sortingOrder = bitStream.ReadIntegerRange(32, -2147483648);
				mask |= 0b00000000000000000000000001000000;
			}
			return (val, mask, null);
		}
		public static (Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180, uint, uint?) DeserializeArchetypeClassic__char_32_Tongue_4a710caa256322a4aa6bfb19109e4559_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180();
			if (bitStream.ReadMask())
			{
				val.startWidth = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.endWidth = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000010;
			}
			if (bitStream.ReadMask())
			{
				val.widthMultiplier = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000100;
			}
			if (bitStream.ReadMask())
			{
				val.startColor = (bitStream.ReadColor(FloatMeta.ForFixedPoint(0, 1, 2.3283064370807973753052522170037E-10))).ToUnityColor();
				mask |= 0b00000000000000000000000000001000;
			}
			if (bitStream.ReadMask())
			{
				val.endColor = (bitStream.ReadColor(FloatMeta.ForFixedPoint(0, 1, 2.3283064370807973753052522170037E-10))).ToUnityColor();
				mask |= 0b00000000000000000000000000010000;
			}
			if (bitStream.ReadMask())
			{
				val.enabled = bitStream.ReadBool();
				mask |= 0b00000000000000000000000000100000;
			}
			if (bitStream.ReadMask())
			{
				val.sortingOrder = bitStream.ReadIntegerRange(32, -2147483648);
				mask |= 0b00000000000000000000000001000000;
			}

			return (val, mask, 0);
		}

		/// <summary>
		/// Resets byte array references to the local array instance that is kept in the lastSentData.
		/// If the array content has changed but remains of same length, the new content is copied into the local array instance.
		/// If the array length has changed, the array is cloned and overwrites the local instance.
		/// If the array has not changed, the reference is reset to the local array instance.
		/// Otherwise, changes to other fields on the component might cause the local array instance reference to become permanently lost.
		/// </summary>
		public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
		{
			var last = lastSent as Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180?;
	
		}
	}
}