// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_47cb5312f9d22b34095ab0d72bfecbcd_641cf119_30b7_40a7_9c8b_6a18e4d55da3 : PositionBinding
	{
		public override string CoherenceComponentName => "WorldPosition";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(coherenceSync.coherencePosition);
			set => coherenceSync.coherencePosition = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((WorldPosition)coherenceComponent).value;
			if (!coherenceSync.HasParentWithCoherenceSync)
            {
                value += floatingOriginDelta;
            }
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (WorldPosition)coherenceComponent;
			update.value = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldPosition();
		}
	}

	public class Binding_47cb5312f9d22b34095ab0d72bfecbcd_70e0ee86_50fc_441d_8b51_706373de0725 : BoolBinding
	{
		private MapBehaviour CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (MapBehaviour)UnityComponent;
		}
		public override string CoherenceComponentName => "Map_MapBehaviour_3964490343674139607";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.enabled);
			set => CastedUnityComponent.enabled = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Map_MapBehaviour_3964490343674139607)coherenceComponent).enabled;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Map_MapBehaviour_3964490343674139607)coherenceComponent;
			update.enabled = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Map_MapBehaviour_3964490343674139607();
		}
	}

	public class Binding_47cb5312f9d22b34095ab0d72bfecbcd_ca65b25b_85d9_4ee7_80ea_14bd3c410b37 : FloatBinding
	{
		private MapBehaviour CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (MapBehaviour)UnityComponent;
		}
		public override string CoherenceComponentName => "Map_MapBehaviour_3964490343674139607";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.minDistanceWithPlayer);
			set => CastedUnityComponent.minDistanceWithPlayer = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Map_MapBehaviour_3964490343674139607)coherenceComponent).minDistanceWithPlayer;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Map_MapBehaviour_3964490343674139607)coherenceComponent;
			update.minDistanceWithPlayer = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Map_MapBehaviour_3964490343674139607();
		}
	}

	public class Binding_47cb5312f9d22b34095ab0d72bfecbcd_b4e68875_6efc_422b_85e0_2a50475d4836 : ReferenceBinding
	{
		private MapBehaviour CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (MapBehaviour)UnityComponent;
		}
		public override string CoherenceComponentName => "Map_MapBehaviour_3964490343674139607";

		public override uint FieldMask => 0b00000000000000000000000000000100;

		public override SerializeEntityID Value
		{
			get => (SerializeEntityID)coherenceSync.MonoBridge.UnityObjectToEntityId(CastedUnityComponent.mapTilesParent);
			set => CastedUnityComponent.mapTilesParent = coherenceSync.MonoBridge.EntityIdToTransform(value);
		}

		protected override SerializeEntityID ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Map_MapBehaviour_3964490343674139607)coherenceComponent).mapTilesParent;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Map_MapBehaviour_3964490343674139607)coherenceComponent;
			update.mapTilesParent = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Map_MapBehaviour_3964490343674139607();
		}
	}


	[Preserve]
	[AddComponentMenu("coherence/Baked/Baked 'Map' (auto assigned)")]
	[RequireComponent(typeof(CoherenceSync))]
	public class CoherenceSyncMap : CoherenceSyncBaked
	{
		private CoherenceSync coherenceSync;
		private Logger logger;

		// Cached targets for commands		
		private MapBehaviour Map_MapBehaviour__char_46_ClearMap_2dc0b920_65b2_4e81_a553_c89faf48edd2_CommandTarget;		
		private MapBehaviour Map_MapBehaviour__char_46_ClearRocks_6603062e_2cf3_4da8_b85d_fb71c91c4334_CommandTarget;		
		private MapBehaviour Map_MapBehaviour__char_46_GenerateNewTilesAroundPosition_fa461b82_7652_4711_a787_f1c1055bbbc2_CommandTarget;
		private InputBuffer<Map> inputBuffer;
		private Map currentInput;
		private long lastAddedFrame = -1;
		private CoherenceInput coherenceInput;
		private long currentSimulationFrame => coherenceInput.CurrentSimulationFrame;

		private IClient client;
		private CoherenceMonoBridge monoBridge => coherenceSync.MonoBridge;

		protected void Awake()
		{
			coherenceSync = GetComponent<CoherenceSync>();
			coherenceSync.usingReflection = false;

			logger = coherenceSync.logger.With<CoherenceSyncMap>();
			if (coherenceSync.TryGetBindingByGuid("2dc0b920-65b2-4e81-a553-c89faf48edd2", "ClearMap", out Binding Map_MapBehaviour__char_46_ClearMap_2dc0b920_65b2_4e81_a553_c89faf48edd2))
			{
				Map_MapBehaviour__char_46_ClearMap_2dc0b920_65b2_4e81_a553_c89faf48edd2_CommandTarget = (MapBehaviour)Map_MapBehaviour__char_46_ClearMap_2dc0b920_65b2_4e81_a553_c89faf48edd2.UnityComponent;
				coherenceSync.AddCommandRequestDelegate("MapBehaviour.ClearMap", "()",
				SendCommand_Map_MapBehaviour__char_46_ClearMap_2dc0b920_65b2_4e81_a553_c89faf48edd2, ReceiveLocalCommand_Map_MapBehaviour__char_46_ClearMap_2dc0b920_65b2_4e81_a553_c89faf48edd2, MessageTarget.All, Map_MapBehaviour__char_46_ClearMap_2dc0b920_65b2_4e81_a553_c89faf48edd2_CommandTarget,false);
			}
			else
			{
				logger.Error("Couldn't find command binding (ClearMap)");
			}
			if (coherenceSync.TryGetBindingByGuid("6603062e-2cf3-4da8-b85d-fb71c91c4334", "ClearRocks", out Binding Map_MapBehaviour__char_46_ClearRocks_6603062e_2cf3_4da8_b85d_fb71c91c4334))
			{
				Map_MapBehaviour__char_46_ClearRocks_6603062e_2cf3_4da8_b85d_fb71c91c4334_CommandTarget = (MapBehaviour)Map_MapBehaviour__char_46_ClearRocks_6603062e_2cf3_4da8_b85d_fb71c91c4334.UnityComponent;
				coherenceSync.AddCommandRequestDelegate("MapBehaviour.ClearRocks", "()",
				SendCommand_Map_MapBehaviour__char_46_ClearRocks_6603062e_2cf3_4da8_b85d_fb71c91c4334, ReceiveLocalCommand_Map_MapBehaviour__char_46_ClearRocks_6603062e_2cf3_4da8_b85d_fb71c91c4334, MessageTarget.All, Map_MapBehaviour__char_46_ClearRocks_6603062e_2cf3_4da8_b85d_fb71c91c4334_CommandTarget,false);
			}
			else
			{
				logger.Error("Couldn't find command binding (ClearRocks)");
			}
			if (coherenceSync.TryGetBindingByGuid("fa461b82-7652-4711-a787-f1c1055bbbc2", "GenerateNewTilesAroundPosition", out Binding Map_MapBehaviour__char_46_GenerateNewTilesAroundPosition_fa461b82_7652_4711_a787_f1c1055bbbc2))
			{
				Map_MapBehaviour__char_46_GenerateNewTilesAroundPosition_fa461b82_7652_4711_a787_f1c1055bbbc2_CommandTarget = (MapBehaviour)Map_MapBehaviour__char_46_GenerateNewTilesAroundPosition_fa461b82_7652_4711_a787_f1c1055bbbc2.UnityComponent;
				coherenceSync.AddCommandRequestDelegate("MapBehaviour.GenerateNewTilesAroundPosition", "(UnityEngine.Vector2)",
				SendCommand_Map_MapBehaviour__char_46_GenerateNewTilesAroundPosition_fa461b82_7652_4711_a787_f1c1055bbbc2, ReceiveLocalCommand_Map_MapBehaviour__char_46_GenerateNewTilesAroundPosition_fa461b82_7652_4711_a787_f1c1055bbbc2, MessageTarget.All, Map_MapBehaviour__char_46_GenerateNewTilesAroundPosition_fa461b82_7652_4711_a787_f1c1055bbbc2_CommandTarget,false);
			}
			else
			{
				logger.Error("Couldn't find command binding (GenerateNewTilesAroundPosition)");
			}
			coherenceInput = coherenceSync.Input;
			inputBuffer = new InputBuffer<Map>(coherenceInput.InitialBufferSize, coherenceInput.InitialBufferDelay, coherenceInput.UseFixedSimulationFrames);
			if (coherenceSync.TryGetBindingByGuid("641cf119-30b7-40a7-9c8b-6a18e4d55da3", "position", out Binding InternalWorldPosition_Translation_value))
			{
				var clone = new Binding_47cb5312f9d22b34095ab0d72bfecbcd_641cf119_30b7_40a7_9c8b_6a18e4d55da3();
				InternalWorldPosition_Translation_value.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalWorldPosition_Translation_value)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).position");
			}
			if (coherenceSync.TryGetBindingByGuid("70e0ee86-50fc-441d-8b51-706373de0725", "enabled", out Binding InternalMap_MapBehaviour_3964490343674139607_Map_MapBehaviour_3964490343674139607_enabled))
			{
				var clone = new Binding_47cb5312f9d22b34095ab0d72bfecbcd_70e0ee86_50fc_441d_8b51_706373de0725();
				InternalMap_MapBehaviour_3964490343674139607_Map_MapBehaviour_3964490343674139607_enabled.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalMap_MapBehaviour_3964490343674139607_Map_MapBehaviour_3964490343674139607_enabled)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (MapBehaviour).enabled");
			}
			if (coherenceSync.TryGetBindingByGuid("ca65b25b-85d9-4ee7-80ea-14bd3c410b37", "minDistanceWithPlayer", out Binding InternalMap_MapBehaviour_3964490343674139607_Map_MapBehaviour_3964490343674139607_minDistanceWithPlayer))
			{
				var clone = new Binding_47cb5312f9d22b34095ab0d72bfecbcd_ca65b25b_85d9_4ee7_80ea_14bd3c410b37();
				InternalMap_MapBehaviour_3964490343674139607_Map_MapBehaviour_3964490343674139607_minDistanceWithPlayer.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalMap_MapBehaviour_3964490343674139607_Map_MapBehaviour_3964490343674139607_minDistanceWithPlayer)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (MapBehaviour).minDistanceWithPlayer");
			}
			if (coherenceSync.TryGetBindingByGuid("b4e68875-6efc-422b-85e0-2a50475d4836", "mapTilesParent", out Binding InternalMap_MapBehaviour_3964490343674139607_Map_MapBehaviour_3964490343674139607_mapTilesParent))
			{
				var clone = new Binding_47cb5312f9d22b34095ab0d72bfecbcd_b4e68875_6efc_422b_85e0_2a50475d4836();
				InternalMap_MapBehaviour_3964490343674139607_Map_MapBehaviour_3964490343674139607_mapTilesParent.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalMap_MapBehaviour_3964490343674139607_Map_MapBehaviour_3964490343674139607_mapTilesParent)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (MapBehaviour).mapTilesParent");
			}
		}

		public override List<ICoherenceComponentData> CreateEntity()
		{
			if (coherenceSync.UsesLODsAtRuntime && (Archetypes.IndexForName.TryGetValue(coherenceSync.Archetype.ArchetypeName, out int archetypeIndex)))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
			else
			{
				logger.Warning($"Unable to find archetype {coherenceSync.Archetype.ArchetypeName} in dictionary. Please, bake manually (coherence > Bake)");
			}

			return null;
		}
		private void OnDestroy()
		{
			if (monoBridge != null)
			{
				monoBridge.OnLateFixedNetworkUpdate -= SendInputState;
			}
		}

		public override void Initialize(CoherenceSync sync, IClient client)
		{
			if (coherenceSync == null)
			{
				coherenceSync = sync;
			}
			this.client = client;
			sync.Input.internalSetButtonState = SetButtonState;
			sync.Input.internalSetButtonRangeState = SetButtonRangeState;
			sync.Input.internalSetAxisState = SetAxisState;
			sync.Input.internalSetStringState = SetStringState;
			sync.Input.internalGetButtonState = GetButtonState;
			sync.Input.internalGetButtonRangeState = GetButtonRangeState;
			sync.Input.internalGetAxisState = GetAxisState;
			sync.Input.internalGetStringState = GetStringState;
			sync.Input.internalRequestBuffer = () => inputBuffer;
			sync.Input.internalOnInputReceived += OnInput;
			sync.Input.internalRequestBuffer = () => inputBuffer;

			if (coherenceInput.UseFixedSimulationFrames)
			{
				sync.MonoBridge.OnLateFixedNetworkUpdate += SendInputState;
			}
		}
		void SendCommand_Map_MapBehaviour__char_46_ClearMap_2dc0b920_65b2_4e81_a553_c89faf48edd2(MessageTarget target, object[] args)
		{
			var command = new Map_MapBehaviour__char_46_ClearMap_2dc0b920_65b2_4e81_a553_c89faf48edd2();
			client.SendCommand(command, target, coherenceSync.EntityID);
		}

		void ReceiveLocalCommand_Map_MapBehaviour__char_46_ClearMap_2dc0b920_65b2_4e81_a553_c89faf48edd2(MessageTarget target, object[] args)
		{
			var command = new Map_MapBehaviour__char_46_ClearMap_2dc0b920_65b2_4e81_a553_c89faf48edd2();
			ReceiveCommand_Map_MapBehaviour__char_46_ClearMap_2dc0b920_65b2_4e81_a553_c89faf48edd2(command);
		}

		void ReceiveCommand_Map_MapBehaviour__char_46_ClearMap_2dc0b920_65b2_4e81_a553_c89faf48edd2(Map_MapBehaviour__char_46_ClearMap_2dc0b920_65b2_4e81_a553_c89faf48edd2 command)
		{
			var target = Map_MapBehaviour__char_46_ClearMap_2dc0b920_65b2_4e81_a553_c89faf48edd2_CommandTarget;
			target.ClearMap();
		}
		void SendCommand_Map_MapBehaviour__char_46_ClearRocks_6603062e_2cf3_4da8_b85d_fb71c91c4334(MessageTarget target, object[] args)
		{
			var command = new Map_MapBehaviour__char_46_ClearRocks_6603062e_2cf3_4da8_b85d_fb71c91c4334();
			client.SendCommand(command, target, coherenceSync.EntityID);
		}

		void ReceiveLocalCommand_Map_MapBehaviour__char_46_ClearRocks_6603062e_2cf3_4da8_b85d_fb71c91c4334(MessageTarget target, object[] args)
		{
			var command = new Map_MapBehaviour__char_46_ClearRocks_6603062e_2cf3_4da8_b85d_fb71c91c4334();
			ReceiveCommand_Map_MapBehaviour__char_46_ClearRocks_6603062e_2cf3_4da8_b85d_fb71c91c4334(command);
		}

		void ReceiveCommand_Map_MapBehaviour__char_46_ClearRocks_6603062e_2cf3_4da8_b85d_fb71c91c4334(Map_MapBehaviour__char_46_ClearRocks_6603062e_2cf3_4da8_b85d_fb71c91c4334 command)
		{
			var target = Map_MapBehaviour__char_46_ClearRocks_6603062e_2cf3_4da8_b85d_fb71c91c4334_CommandTarget;
			target.ClearRocks();
		}
		void SendCommand_Map_MapBehaviour__char_46_GenerateNewTilesAroundPosition_fa461b82_7652_4711_a787_f1c1055bbbc2(MessageTarget target, object[] args)
		{
			var command = new Map_MapBehaviour__char_46_GenerateNewTilesAroundPosition_fa461b82_7652_4711_a787_f1c1055bbbc2();
			int i = 0;
			command.position = (Vector2)((UnityEngine.Vector2)args[i++]);
			client.SendCommand(command, target, coherenceSync.EntityID);
		}

		void ReceiveLocalCommand_Map_MapBehaviour__char_46_GenerateNewTilesAroundPosition_fa461b82_7652_4711_a787_f1c1055bbbc2(MessageTarget target, object[] args)
		{
			var command = new Map_MapBehaviour__char_46_GenerateNewTilesAroundPosition_fa461b82_7652_4711_a787_f1c1055bbbc2();
			int i = 0;
			command.position = (Vector2)((UnityEngine.Vector2)args[i++]);
			ReceiveCommand_Map_MapBehaviour__char_46_GenerateNewTilesAroundPosition_fa461b82_7652_4711_a787_f1c1055bbbc2(command);
		}

		void ReceiveCommand_Map_MapBehaviour__char_46_GenerateNewTilesAroundPosition_fa461b82_7652_4711_a787_f1c1055bbbc2(Map_MapBehaviour__char_46_GenerateNewTilesAroundPosition_fa461b82_7652_4711_a787_f1c1055bbbc2 command)
		{
			var target = Map_MapBehaviour__char_46_GenerateNewTilesAroundPosition_fa461b82_7652_4711_a787_f1c1055bbbc2_CommandTarget;
			target.GenerateNewTilesAroundPosition((UnityEngine.Vector2)(command.position));
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				case Map_MapBehaviour__char_46_ClearMap_2dc0b920_65b2_4e81_a553_c89faf48edd2 castedCommand:
					ReceiveCommand_Map_MapBehaviour__char_46_ClearMap_2dc0b920_65b2_4e81_a553_c89faf48edd2(castedCommand);
					break;
				case Map_MapBehaviour__char_46_ClearRocks_6603062e_2cf3_4da8_b85d_fb71c91c4334 castedCommand:
					ReceiveCommand_Map_MapBehaviour__char_46_ClearRocks_6603062e_2cf3_4da8_b85d_fb71c91c4334(castedCommand);
					break;
				case Map_MapBehaviour__char_46_GenerateNewTilesAroundPosition_fa461b82_7652_4711_a787_f1c1055bbbc2 castedCommand:
					ReceiveCommand_Map_MapBehaviour__char_46_GenerateNewTilesAroundPosition_fa461b82_7652_4711_a787_f1c1055bbbc2(castedCommand);
					break;
				default:
					logger.Warning($"[CoherenceSyncMap] Unhandled command: {command.GetType()}.");
					break;
			}
		}

		private void SetButtonState(string name, bool value)
		{
			switch(name)
			{
				default:
					logger.Error($"No input button of name: {name}");
					break;
			}
		}

		private void SetButtonRangeState(string name, float value)
		{
			switch(name)
			{
			default:
				logger.Error($"No input button range of name: {name}");
				break;
			}
		}

		private void SetAxisState(string name, Vector2 value)
		{
			switch(name)
			{
			default:
				logger.Error($"No input axis of name: {name}");
				break;
			}
		}

		private void SetStringState(string name, string value)
		{
			switch(name)
			{
				default:
					logger.Error($"No input button of name: {name}");
					break;
			}
		}

		public override void SendInputState()
		{
			if (!coherenceInput.IsProducer || !coherenceInput.IsReadyToProcessInputs || !coherenceInput.IsInputOwner)
			{
				return;
			}

			if (lastAddedFrame != currentSimulationFrame)
			{
				inputBuffer.AddInput(currentInput, currentSimulationFrame);
				lastAddedFrame = currentSimulationFrame;
			}

			while (inputBuffer.DequeueForSending(currentSimulationFrame, out long frameToSend, out Map input, out bool differs))
			{
				coherenceInput.DebugOnInputSent(frameToSend, input);
				client.SendInput(input, frameToSend, coherenceSync.EntityID);
			}
		}

		private bool ShouldPollCurrentInput(long frame)
		{
			return coherenceInput.IsProducer && coherenceInput.Delay == 0 && frame == currentSimulationFrame;
		}

		private bool GetButtonState(string name, long? simulationFrame)
		{
			long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);

			switch(name)
			{
				default:
					logger.Error($"No input button of name: {name}");
					break;
			}

			return false;
		}

		private float GetButtonRangeState(string name, long? simulationFrame)
		{
			long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);

			switch(name)
			{
			default:
				logger.Error($"No input button range of name: {name}");
				break;
			}

			return 0f;
		}

		private Vector2 GetAxisState(string name, long? simulationFrame)
		{
			long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);

			switch(name)
			{
			default:
				logger.Error($"No input axis of name: {name}");
				break;
			}

			return Vector2.zero;
		}

		private string GetStringState(string name, long? simulationFrame)
		{
			long frame = simulationFrame.GetValueOrDefault(currentSimulationFrame);

			switch(name)
			{
				default:
					logger.Error($"No input button of name: {name}");
					break;
			}

			return null;
		}

		private void OnInput(IEntityInput entityInput, long frame)
		{
			var input = (Map)entityInput;
			coherenceInput.DebugOnInputReceived(frame, entityInput);
			inputBuffer.ReceiveInput(input, frame);
		}
	}
}
