// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_4a710caa256322a4aa6bfb19109e4559_4a65e33a_317e_4152_a55e_9994503dd984 : PositionBinding
	{
		public override string CoherenceComponentName => "WorldPosition";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(coherenceSync.coherencePosition);
			set => coherenceSync.coherencePosition = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((WorldPosition)coherenceComponent).value;
			if (!coherenceSync.HasParentWithCoherenceSync)
            {
                value += floatingOriginDelta;
            }
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (WorldPosition)coherenceComponent;
			update.value = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldPosition();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_b34fd4f3_5734_49d1_ba6b_62efb5c741e5 : RotationBinding
	{
		public override string CoherenceComponentName => "WorldOrientation";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Quaternion Value
		{
			get => (Quaternion)(UnityEngine.Quaternion)(coherenceSync.coherenceRotation);
			set => coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value);
		}

		protected override Quaternion ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((WorldOrientation)coherenceComponent).value;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (WorldOrientation)coherenceComponent;
			update.value = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldOrientation();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_05ae5ff4_186b_45c5_8e50_ff5161397079 : ScaleBinding
	{
		public override string CoherenceComponentName => "GenericScale";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(coherenceSync.coherenceLocalScale);
			set => coherenceSync.coherenceLocalScale = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((GenericScale)coherenceComponent).value;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (GenericScale)coherenceComponent;
			update.value = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new GenericScale();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_883af2bf_38a7_47f1_8285_78fbfd03f86b : FloatBinding
	{
		private UnityEngine.LineRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.LineRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.startWidth);
			set => CastedUnityComponent.startWidth = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931)coherenceComponent).startWidth;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931)coherenceComponent;
			update.startWidth = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_8f5a4b3a_de89_4100_a999_e33689ed863c : FloatBinding
	{
		private UnityEngine.LineRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.LineRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.endWidth);
			set => CastedUnityComponent.endWidth = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931)coherenceComponent).endWidth;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931)coherenceComponent;
			update.endWidth = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_6f44c638_c1f2_43bd_af44_6647ba6c532c : FloatBinding
	{
		private UnityEngine.LineRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.LineRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931";

		public override uint FieldMask => 0b00000000000000000000000000000100;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.widthMultiplier);
			set => CastedUnityComponent.widthMultiplier = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931)coherenceComponent).widthMultiplier;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931)coherenceComponent;
			update.widthMultiplier = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_c4fb51a1_5f32_47cf_93e4_6134f4fdc738 : BoolBinding
	{
		private UnityEngine.LineRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.LineRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931";

		public override uint FieldMask => 0b00000000000000000000000000001000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.enabled);
			set => CastedUnityComponent.enabled = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931)coherenceComponent).enabled;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931)coherenceComponent;
			update.enabled = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_11f3b364_dcaf_4209_974a_0a08f6c9fa92 : FloatBinding
	{
		private UnityEngine.LineRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.LineRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.startWidth);
			set => CastedUnityComponent.startWidth = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180)coherenceComponent).startWidth;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180)coherenceComponent;
			update.startWidth = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_de23c606_41c3_479d_8e99_43c1f397f8b0 : FloatBinding
	{
		private UnityEngine.LineRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.LineRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.endWidth);
			set => CastedUnityComponent.endWidth = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180)coherenceComponent).endWidth;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180)coherenceComponent;
			update.endWidth = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_b33ac8c1_23f4_4f6c_b201_616ef73c9a60 : FloatBinding
	{
		private UnityEngine.LineRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.LineRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180";

		public override uint FieldMask => 0b00000000000000000000000000000100;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.widthMultiplier);
			set => CastedUnityComponent.widthMultiplier = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180)coherenceComponent).widthMultiplier;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180)coherenceComponent;
			update.widthMultiplier = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_2f05599f_56ce_40fa_8585_22b41ae444f8 : ColorBinding
	{
		private UnityEngine.LineRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.LineRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180";

		public override uint FieldMask => 0b00000000000000000000000000001000;

		public override Color Value
		{
			get => (Color)(UnityEngine.Color)(CastedUnityComponent.startColor);
			set => CastedUnityComponent.startColor = (UnityEngine.Color)(value);
		}

		protected override Color ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180)coherenceComponent).startColor;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180)coherenceComponent;
			update.startColor = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_284aea37_e770_4a90_9fb0_40e79c45d185 : ColorBinding
	{
		private UnityEngine.LineRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.LineRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180";

		public override uint FieldMask => 0b00000000000000000000000000010000;

		public override Color Value
		{
			get => (Color)(UnityEngine.Color)(CastedUnityComponent.endColor);
			set => CastedUnityComponent.endColor = (UnityEngine.Color)(value);
		}

		protected override Color ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180)coherenceComponent).endColor;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180)coherenceComponent;
			update.endColor = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_0abfe209_b235_40d8_8852_ec9114f55b24 : BoolBinding
	{
		private UnityEngine.LineRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.LineRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180";

		public override uint FieldMask => 0b00000000000000000000000000100000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.enabled);
			set => CastedUnityComponent.enabled = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180)coherenceComponent).enabled;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180)coherenceComponent;
			update.enabled = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_749ed683_cf1a_4667_9cae_e4b453be7b76 : IntBinding
	{
		private UnityEngine.LineRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.LineRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180";

		public override uint FieldMask => 0b00000000000000000000000001000000;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.sortingOrder);
			set => CastedUnityComponent.sortingOrder = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180)coherenceComponent).sortingOrder;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180)coherenceComponent;
			update.sortingOrder = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_73ed0458_d777_4e98_bcc4_369bf7d7cc68 : DeepPositionBinding
	{
		private UnityEngine.Transform CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_UnityEngine__char_46_Transform_3990334963750023930";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(CastedUnityComponent.localPosition);
			set => CastedUnityComponent.localPosition = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_UnityEngine__char_46_Transform_3990334963750023930)coherenceComponent).position;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_UnityEngine__char_46_Transform_3990334963750023930)coherenceComponent;
			update.position = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_UnityEngine__char_46_Transform_3990334963750023930();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_4b1b8367_3807_4f57_b44e_00334cf4ec41 : DeepRotationBinding
	{
		private UnityEngine.Transform CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_UnityEngine__char_46_Transform_3990334963750023930";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override Quaternion Value
		{
			get => (Quaternion)(UnityEngine.Quaternion)(CastedUnityComponent.localRotation);
			set => CastedUnityComponent.localRotation = (UnityEngine.Quaternion)(value);
		}

		protected override Quaternion ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_UnityEngine__char_46_Transform_3990334963750023930)coherenceComponent).rotation;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_UnityEngine__char_46_Transform_3990334963750023930)coherenceComponent;
			update.rotation = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_UnityEngine__char_46_Transform_3990334963750023930();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_1981a485_338b_4e27_afb5_9205cace448f : DeepScaleBinding
	{
		private UnityEngine.Transform CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_UnityEngine__char_46_Transform_3990334963750023930";

		public override uint FieldMask => 0b00000000000000000000000000000100;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(CastedUnityComponent.localScale);
			set => CastedUnityComponent.localScale = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_UnityEngine__char_46_Transform_3990334963750023930)coherenceComponent).localScale;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_UnityEngine__char_46_Transform_3990334963750023930)coherenceComponent;
			update.localScale = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_UnityEngine__char_46_Transform_3990334963750023930();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_3be3222c_594c_4ffb_9519_9c5743c9955d : FloatBinding
	{
		private WeaponBehaviour CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (WeaponBehaviour)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.tongueWidth);
			set => CastedUnityComponent.tongueWidth = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent).tongueWidth;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent;
			update.tongueWidth = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_e3a19960_91f5_448f_813c_67de1dc6f3b6 : ColorBinding
	{
		private WeaponBehaviour CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (WeaponBehaviour)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override Color Value
		{
			get => (Color)(UnityEngine.Color)(CastedUnityComponent.outlineColor);
			set => CastedUnityComponent.outlineColor = (UnityEngine.Color)(value);
		}

		protected override Color ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent).outlineColor;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent;
			update.outlineColor = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_7d16b6f6_ce31_46d1_8911_7a4b8e2e2139 : FloatBinding
	{
		private WeaponBehaviour CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (WeaponBehaviour)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178";

		public override uint FieldMask => 0b00000000000000000000000000000100;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.outlineWeight);
			set => CastedUnityComponent.outlineWeight = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent).outlineWeight;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent;
			update.outlineWeight = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_bb74b964_9ec1_43d9_933c_8acb89aa22aa : FloatBinding
	{
		private WeaponBehaviour CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (WeaponBehaviour)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178";

		public override uint FieldMask => 0b00000000000000000000000000001000;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.cooldown);
			set => CastedUnityComponent.cooldown = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent).cooldown;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent;
			update.cooldown = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_d49adfed_a1a3_4789_8e13_23ca4eb93bce : FloatBinding
	{
		private WeaponBehaviour CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (WeaponBehaviour)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178";

		public override uint FieldMask => 0b00000000000000000000000000010000;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.attackSpeed);
			set => CastedUnityComponent.attackSpeed = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent).attackSpeed;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent;
			update.attackSpeed = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_ed94d144_b63c_4ccd_96ec_0d86dd8b903a : FloatBinding
	{
		private WeaponBehaviour CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (WeaponBehaviour)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178";

		public override uint FieldMask => 0b00000000000000000000000000100000;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.range);
			set => CastedUnityComponent.range = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent).range;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent;
			update.range = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_9d4081a9_0bff_4d2a_b85d_cbb941cd9cbf : FloatBinding
	{
		private WeaponBehaviour CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (WeaponBehaviour)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178";

		public override uint FieldMask => 0b00000000000000000000000001000000;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.duration);
			set => CastedUnityComponent.duration = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent).duration;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent;
			update.duration = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_231fa084_b007_4b3d_9440_b14450793ee5 : FloatBinding
	{
		private WeaponBehaviour CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (WeaponBehaviour)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178";

		public override uint FieldMask => 0b00000000000000000000000010000000;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.knockbackForce);
			set => CastedUnityComponent.knockbackForce = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent).knockbackForce;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent;
			update.knockbackForce = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_b2bae55f_a043_4f19_97b6_53bf75c3ecbb : FloatBinding
	{
		private WeaponBehaviour CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (WeaponBehaviour)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178";

		public override uint FieldMask => 0b00000000000000000000000100000000;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.damage);
			set => CastedUnityComponent.damage = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent).damage;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent;
			update.damage = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_72defefd_ae23_4af8_840b_aa8874892dd2 : FloatBinding
	{
		private WeaponBehaviour CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (WeaponBehaviour)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178";

		public override uint FieldMask => 0b00000000000000000000001000000000;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.healthAbsorbRatio);
			set => CastedUnityComponent.healthAbsorbRatio = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent).healthAbsorbRatio;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent;
			update.healthAbsorbRatio = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_5d2b1954_dbc4_4330_8e9f_0d6a95bf7ddd : FloatBinding
	{
		private WeaponBehaviour CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (WeaponBehaviour)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178";

		public override uint FieldMask => 0b00000000000000000000010000000000;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.poisonDamage);
			set => CastedUnityComponent.poisonDamage = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent).poisonDamage;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent;
			update.poisonDamage = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_f03ff6a8_8e40_4594_b313_d628fe66f323 : BoolBinding
	{
		private WeaponBehaviour CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (WeaponBehaviour)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178";

		public override uint FieldMask => 0b00000000000000000000100000000000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.freezeEffect);
			set => CastedUnityComponent.freezeEffect = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent).freezeEffect;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent;
			update.freezeEffect = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_d6f2503f_f4c1_4e5b_afdb_c7a52640c789 : FloatBinding
	{
		private WeaponBehaviour CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (WeaponBehaviour)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178";

		public override uint FieldMask => 0b00000000000000000001000000000000;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.curseChance);
			set => CastedUnityComponent.curseChance = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent).curseChance;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent;
			update.curseChance = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_06540550_dd51_49fa_90b4_b7c50222d95e : FloatBinding
	{
		private WeaponBehaviour CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (WeaponBehaviour)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178";

		public override uint FieldMask => 0b00000000000000000010000000000000;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.lastAttackTime);
			set => CastedUnityComponent.lastAttackTime = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent).lastAttackTime;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent;
			update.lastAttackTime = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_82ffbf4b_aa50_4b21_9f97_b9c8a7a3fee7 : BoolBinding
	{
		private WeaponBehaviour CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (WeaponBehaviour)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178";

		public override uint FieldMask => 0b00000000000000000100000000000000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.isAttacking);
			set => CastedUnityComponent.isAttacking = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent).isAttacking;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent;
			update.isAttacking = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_3c7bde53_430d_4310_82ea_c05545d075b6 : BoolBinding
	{
		private WeaponBehaviour CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (WeaponBehaviour)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178";

		public override uint FieldMask => 0b00000000000000001000000000000000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.preventAttack);
			set => CastedUnityComponent.preventAttack = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent).preventAttack;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent;
			update.preventAttack = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_908a2365_0277_432c_8e60_0f92a7026d4e : IntBinding
	{
		private WeaponBehaviour CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (WeaponBehaviour)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178";

		public override uint FieldMask => 0b00000000000000010000000000000000;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.tongueTypeIndex);
			set => CastedUnityComponent.tongueTypeIndex = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent).tongueTypeIndex;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent;
			update.tongueTypeIndex = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_9699a96a_85f0_42a2_8a3e_fc8db60122b7 : IntBinding
	{
		private WeaponBehaviour CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (WeaponBehaviour)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178";

		public override uint FieldMask => 0b00000000000000100000000000000000;

		public override int Value
		{
			get => (int)(System.Int32)(CastedUnityComponent.tongueTypeCount);
			set => CastedUnityComponent.tongueTypeCount = (System.Int32)(value);
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent).tongueTypeCount;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent;
			update.tongueTypeCount = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178();
		}
	}

	public class Binding_4a710caa256322a4aa6bfb19109e4559_d9d837cb_74b5_4205_be4e_a0868b1956b6 : BoolBinding
	{
		private WeaponBehaviour CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (WeaponBehaviour)UnityComponent;
		}
		public override string CoherenceComponentName => "Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178";

		public override uint FieldMask => 0b00000000000001000000000000000000;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.enabled);
			set => CastedUnityComponent.enabled = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent).enabled;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178)coherenceComponent;
			update.enabled = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178();
		}
	}


	[Preserve]
	[AddComponentMenu("coherence/Baked/Baked 'Classic Tongue' (auto assigned)")]
	[RequireComponent(typeof(CoherenceSync))]
	public class CoherenceSyncClassic__char_32_Tongue : CoherenceSyncBaked
	{
		private CoherenceSync coherenceSync;
		private Logger logger;

		// Cached targets for commands

		private IClient client;
		private CoherenceMonoBridge monoBridge => coherenceSync.MonoBridge;

		protected void Awake()
		{
			coherenceSync = GetComponent<CoherenceSync>();
			coherenceSync.usingReflection = false;

			logger = coherenceSync.logger.With<CoherenceSyncClassic__char_32_Tongue>();
			if (coherenceSync.TryGetBindingByGuid("4a65e33a-317e-4152-a55e-9994503dd984", "position", out Binding InternalWorldPosition_Translation_value))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_4a65e33a_317e_4152_a55e_9994503dd984();
				InternalWorldPosition_Translation_value.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalWorldPosition_Translation_value)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).position");
			}
			if (coherenceSync.TryGetBindingByGuid("b34fd4f3-5734-49d1-ba6b-62efb5c741e5", "rotation", out Binding InternalWorldOrientation_Rotation_value))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_b34fd4f3_5734_49d1_ba6b_62efb5c741e5();
				InternalWorldOrientation_Rotation_value.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalWorldOrientation_Rotation_value)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).rotation");
			}
			if (coherenceSync.TryGetBindingByGuid("05ae5ff4-186b-45c5-8e50-ff5161397079", "localScale", out Binding InternalGenericScale_GenericScale_value))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_05ae5ff4_186b_45c5_8e50_ff5161397079();
				InternalGenericScale_GenericScale_value.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalGenericScale_GenericScale_value)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).localScale");
			}
			if (coherenceSync.TryGetBindingByGuid("883af2bf-38a7-47f1-8285-78fbfd03f86b", "startWidth", out Binding InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931_startWidth))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_883af2bf_38a7_47f1_8285_78fbfd03f86b();
				InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931_startWidth.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931_startWidth)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.LineRenderer).startWidth");
			}
			if (coherenceSync.TryGetBindingByGuid("8f5a4b3a-de89-4100-a999-e33689ed863c", "endWidth", out Binding InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931_endWidth))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_8f5a4b3a_de89_4100_a999_e33689ed863c();
				InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931_endWidth.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931_endWidth)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.LineRenderer).endWidth");
			}
			if (coherenceSync.TryGetBindingByGuid("6f44c638-c1f2-43bd-af44-6647ba6c532c", "widthMultiplier", out Binding InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931_widthMultiplier))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_6f44c638_c1f2_43bd_af44_6647ba6c532c();
				InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931_widthMultiplier.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931_widthMultiplier)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.LineRenderer).widthMultiplier");
			}
			if (coherenceSync.TryGetBindingByGuid("c4fb51a1-5f32-47cf-93e4-6134f4fdc738", "enabled", out Binding InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931_enabled))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_c4fb51a1_5f32_47cf_93e4_6134f4fdc738();
				InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931_enabled.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334963750023931_enabled)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.LineRenderer).enabled");
			}
			if (coherenceSync.TryGetBindingByGuid("11f3b364-dcaf-4209-974a-0a08f6c9fa92", "startWidth", out Binding InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_startWidth))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_11f3b364_dcaf_4209_974a_0a08f6c9fa92();
				InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_startWidth.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_startWidth)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.LineRenderer).startWidth");
			}
			if (coherenceSync.TryGetBindingByGuid("de23c606-41c3-479d-8e99-43c1f397f8b0", "endWidth", out Binding InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_endWidth))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_de23c606_41c3_479d_8e99_43c1f397f8b0();
				InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_endWidth.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_endWidth)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.LineRenderer).endWidth");
			}
			if (coherenceSync.TryGetBindingByGuid("b33ac8c1-23f4-4f6c-b201-616ef73c9a60", "widthMultiplier", out Binding InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_widthMultiplier))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_b33ac8c1_23f4_4f6c_b201_616ef73c9a60();
				InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_widthMultiplier.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_widthMultiplier)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.LineRenderer).widthMultiplier");
			}
			if (coherenceSync.TryGetBindingByGuid("2f05599f-56ce-40fa-8585-22b41ae444f8", "startColor", out Binding InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_startColor))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_2f05599f_56ce_40fa_8585_22b41ae444f8();
				InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_startColor.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_startColor)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.LineRenderer).startColor");
			}
			if (coherenceSync.TryGetBindingByGuid("284aea37-e770-4a90-9fb0-40e79c45d185", "endColor", out Binding InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_endColor))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_284aea37_e770_4a90_9fb0_40e79c45d185();
				InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_endColor.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_endColor)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.LineRenderer).endColor");
			}
			if (coherenceSync.TryGetBindingByGuid("0abfe209-b235-40d8-8852-ec9114f55b24", "enabled", out Binding InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_enabled))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_0abfe209_b235_40d8_8852_ec9114f55b24();
				InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_enabled.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_enabled)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.LineRenderer).enabled");
			}
			if (coherenceSync.TryGetBindingByGuid("749ed683-cf1a-4667-9cae-e4b453be7b76", "sortingOrder", out Binding InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_sortingOrder))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_749ed683_cf1a_4667_9cae_e4b453be7b76();
				InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_sortingOrder.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_Classic__char_32_Tongue_UnityEngine__char_46_LineRenderer_3990334965163639180_sortingOrder)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.LineRenderer).sortingOrder");
			}
			if (coherenceSync.TryGetBindingByGuid("73ed0458-d777-4e98-bcc4-369bf7d7cc68", "position", out Binding InternalClassic__char_32_Tongue_UnityEngine__char_46_Transform_3990334963750023930_Classic__char_32_Tongue_UnityEngine__char_46_Transform_3990334963750023930_position))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_73ed0458_d777_4e98_bcc4_369bf7d7cc68();
				InternalClassic__char_32_Tongue_UnityEngine__char_46_Transform_3990334963750023930_Classic__char_32_Tongue_UnityEngine__char_46_Transform_3990334963750023930_position.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_UnityEngine__char_46_Transform_3990334963750023930_Classic__char_32_Tongue_UnityEngine__char_46_Transform_3990334963750023930_position)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).position");
			}
			if (coherenceSync.TryGetBindingByGuid("4b1b8367-3807-4f57-b44e-00334cf4ec41", "rotation", out Binding InternalClassic__char_32_Tongue_UnityEngine__char_46_Transform_3990334963750023930_Classic__char_32_Tongue_UnityEngine__char_46_Transform_3990334963750023930_rotation))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_4b1b8367_3807_4f57_b44e_00334cf4ec41();
				InternalClassic__char_32_Tongue_UnityEngine__char_46_Transform_3990334963750023930_Classic__char_32_Tongue_UnityEngine__char_46_Transform_3990334963750023930_rotation.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_UnityEngine__char_46_Transform_3990334963750023930_Classic__char_32_Tongue_UnityEngine__char_46_Transform_3990334963750023930_rotation)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).rotation");
			}
			if (coherenceSync.TryGetBindingByGuid("1981a485-338b-4e27-afb5-9205cace448f", "localScale", out Binding InternalClassic__char_32_Tongue_UnityEngine__char_46_Transform_3990334963750023930_Classic__char_32_Tongue_UnityEngine__char_46_Transform_3990334963750023930_localScale))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_1981a485_338b_4e27_afb5_9205cace448f();
				InternalClassic__char_32_Tongue_UnityEngine__char_46_Transform_3990334963750023930_Classic__char_32_Tongue_UnityEngine__char_46_Transform_3990334963750023930_localScale.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_UnityEngine__char_46_Transform_3990334963750023930_Classic__char_32_Tongue_UnityEngine__char_46_Transform_3990334963750023930_localScale)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).localScale");
			}
			if (coherenceSync.TryGetBindingByGuid("3be3222c-594c-4ffb-9519-9c5743c9955d", "tongueWidth", out Binding InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_tongueWidth))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_3be3222c_594c_4ffb_9519_9c5743c9955d();
				InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_tongueWidth.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_tongueWidth)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (WeaponBehaviour).tongueWidth");
			}
			if (coherenceSync.TryGetBindingByGuid("e3a19960-91f5-448f-813c-67de1dc6f3b6", "outlineColor", out Binding InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_outlineColor))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_e3a19960_91f5_448f_813c_67de1dc6f3b6();
				InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_outlineColor.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_outlineColor)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (WeaponBehaviour).outlineColor");
			}
			if (coherenceSync.TryGetBindingByGuid("7d16b6f6-ce31-46d1-8911-7a4b8e2e2139", "outlineWeight", out Binding InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_outlineWeight))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_7d16b6f6_ce31_46d1_8911_7a4b8e2e2139();
				InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_outlineWeight.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_outlineWeight)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (WeaponBehaviour).outlineWeight");
			}
			if (coherenceSync.TryGetBindingByGuid("bb74b964-9ec1-43d9-933c-8acb89aa22aa", "cooldown", out Binding InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_cooldown))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_bb74b964_9ec1_43d9_933c_8acb89aa22aa();
				InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_cooldown.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_cooldown)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (WeaponBehaviour).cooldown");
			}
			if (coherenceSync.TryGetBindingByGuid("d49adfed-a1a3-4789-8e13-23ca4eb93bce", "attackSpeed", out Binding InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_attackSpeed))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_d49adfed_a1a3_4789_8e13_23ca4eb93bce();
				InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_attackSpeed.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_attackSpeed)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (WeaponBehaviour).attackSpeed");
			}
			if (coherenceSync.TryGetBindingByGuid("ed94d144-b63c-4ccd-96ec-0d86dd8b903a", "range", out Binding InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_range))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_ed94d144_b63c_4ccd_96ec_0d86dd8b903a();
				InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_range.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_range)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (WeaponBehaviour).range");
			}
			if (coherenceSync.TryGetBindingByGuid("9d4081a9-0bff-4d2a-b85d-cbb941cd9cbf", "duration", out Binding InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_duration))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_9d4081a9_0bff_4d2a_b85d_cbb941cd9cbf();
				InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_duration.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_duration)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (WeaponBehaviour).duration");
			}
			if (coherenceSync.TryGetBindingByGuid("231fa084-b007-4b3d-9440-b14450793ee5", "knockbackForce", out Binding InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_knockbackForce))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_231fa084_b007_4b3d_9440_b14450793ee5();
				InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_knockbackForce.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_knockbackForce)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (WeaponBehaviour).knockbackForce");
			}
			if (coherenceSync.TryGetBindingByGuid("b2bae55f-a043-4f19-97b6-53bf75c3ecbb", "damage", out Binding InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_damage))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_b2bae55f_a043_4f19_97b6_53bf75c3ecbb();
				InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_damage.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_damage)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (WeaponBehaviour).damage");
			}
			if (coherenceSync.TryGetBindingByGuid("72defefd-ae23-4af8-840b-aa8874892dd2", "healthAbsorbRatio", out Binding InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_healthAbsorbRatio))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_72defefd_ae23_4af8_840b_aa8874892dd2();
				InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_healthAbsorbRatio.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_healthAbsorbRatio)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (WeaponBehaviour).healthAbsorbRatio");
			}
			if (coherenceSync.TryGetBindingByGuid("5d2b1954-dbc4-4330-8e9f-0d6a95bf7ddd", "poisonDamage", out Binding InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_poisonDamage))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_5d2b1954_dbc4_4330_8e9f_0d6a95bf7ddd();
				InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_poisonDamage.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_poisonDamage)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (WeaponBehaviour).poisonDamage");
			}
			if (coherenceSync.TryGetBindingByGuid("f03ff6a8-8e40-4594-b313-d628fe66f323", "freezeEffect", out Binding InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_freezeEffect))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_f03ff6a8_8e40_4594_b313_d628fe66f323();
				InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_freezeEffect.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_freezeEffect)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (WeaponBehaviour).freezeEffect");
			}
			if (coherenceSync.TryGetBindingByGuid("d6f2503f-f4c1-4e5b-afdb-c7a52640c789", "curseChance", out Binding InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_curseChance))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_d6f2503f_f4c1_4e5b_afdb_c7a52640c789();
				InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_curseChance.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_curseChance)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (WeaponBehaviour).curseChance");
			}
			if (coherenceSync.TryGetBindingByGuid("06540550-dd51-49fa-90b4-b7c50222d95e", "lastAttackTime", out Binding InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_lastAttackTime))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_06540550_dd51_49fa_90b4_b7c50222d95e();
				InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_lastAttackTime.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_lastAttackTime)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (WeaponBehaviour).lastAttackTime");
			}
			if (coherenceSync.TryGetBindingByGuid("82ffbf4b-aa50-4b21-9f97-b9c8a7a3fee7", "isAttacking", out Binding InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_isAttacking))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_82ffbf4b_aa50_4b21_9f97_b9c8a7a3fee7();
				InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_isAttacking.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_isAttacking)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (WeaponBehaviour).isAttacking");
			}
			if (coherenceSync.TryGetBindingByGuid("3c7bde53-430d-4310-82ea-c05545d075b6", "preventAttack", out Binding InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_preventAttack))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_3c7bde53_430d_4310_82ea_c05545d075b6();
				InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_preventAttack.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_preventAttack)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (WeaponBehaviour).preventAttack");
			}
			if (coherenceSync.TryGetBindingByGuid("908a2365-0277-432c-8e60-0f92a7026d4e", "tongueTypeIndex", out Binding InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_tongueTypeIndex))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_908a2365_0277_432c_8e60_0f92a7026d4e();
				InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_tongueTypeIndex.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_tongueTypeIndex)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (WeaponBehaviour).tongueTypeIndex");
			}
			if (coherenceSync.TryGetBindingByGuid("9699a96a-85f0-42a2-8a3e-fc8db60122b7", "tongueTypeCount", out Binding InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_tongueTypeCount))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_9699a96a_85f0_42a2_8a3e_fc8db60122b7();
				InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_tongueTypeCount.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_tongueTypeCount)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (WeaponBehaviour).tongueTypeCount");
			}
			if (coherenceSync.TryGetBindingByGuid("d9d837cb-74b5-4205-be4e-a0868b1956b6", "enabled", out Binding InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_enabled))
			{
				var clone = new Binding_4a710caa256322a4aa6bfb19109e4559_d9d837cb_74b5_4205_be4e_a0868b1956b6();
				InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_enabled.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalClassic__char_32_Tongue_WeaponBehaviour_3990334965163639178_Classic__char_32_Tongue_WeaponBehaviour_3990334965163639178_enabled)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (WeaponBehaviour).enabled");
			}
		}

		public override List<ICoherenceComponentData> CreateEntity()
		{
			if (coherenceSync.UsesLODsAtRuntime && (Archetypes.IndexForName.TryGetValue(coherenceSync.Archetype.ArchetypeName, out int archetypeIndex)))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
			else
			{
				logger.Warning($"Unable to find archetype {coherenceSync.Archetype.ArchetypeName} in dictionary. Please, bake manually (coherence > Bake)");
			}

			return null;
		}

		public override void Initialize(CoherenceSync sync, IClient client)
		{
			if (coherenceSync == null)
			{
				coherenceSync = sync;
			}
			this.client = client;
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				default:
					logger.Warning($"[CoherenceSyncClassic__char_32_Tongue] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
