// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_ef7ce5f54c7d78b479854b7248d15c5a_b5eae117_ad0b_4dbb_af1c_17c36e143c31 : PositionBinding
	{
		public override string CoherenceComponentName => "WorldPosition";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(coherenceSync.coherencePosition);
			set => coherenceSync.coherencePosition = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((WorldPosition)coherenceComponent).value;
			if (!coherenceSync.HasParentWithCoherenceSync)
            {
                value += floatingOriginDelta;
            }
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (WorldPosition)coherenceComponent;
			update.value = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldPosition();
		}
	}

	public class Binding_ef7ce5f54c7d78b479854b7248d15c5a_4b2dbcaa_589a_4ed2_a802_76d495bf93e2 : RotationBinding
	{
		public override string CoherenceComponentName => "WorldOrientation";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Quaternion Value
		{
			get => (Quaternion)(UnityEngine.Quaternion)(coherenceSync.coherenceRotation);
			set => coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value);
		}

		protected override Quaternion ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((WorldOrientation)coherenceComponent).value;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (WorldOrientation)coherenceComponent;
			update.value = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldOrientation();
		}
	}

	public class Binding_ef7ce5f54c7d78b479854b7248d15c5a_779b4dd7_cf60_436e_a4e9_1bcbe3f5fbab : ReferenceBinding
	{
		private FrogCharacterController CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (FrogCharacterController)UnityComponent;
		}
		public override string CoherenceComponentName => "Character_FrogCharacterController_4441217298144173242";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override SerializeEntityID Value
		{
			get => (SerializeEntityID)coherenceSync.MonoBridge.UnityObjectToEntityId(CastedUnityComponent.weaponStartPoint);
			set => CastedUnityComponent.weaponStartPoint = coherenceSync.MonoBridge.EntityIdToTransform(value);
		}

		protected override SerializeEntityID ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Character_FrogCharacterController_4441217298144173242)coherenceComponent).weaponStartPoint;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Character_FrogCharacterController_4441217298144173242)coherenceComponent;
			update.weaponStartPoint = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Character_FrogCharacterController_4441217298144173242();
		}
	}

	public class Binding_ef7ce5f54c7d78b479854b7248d15c5a_c48e1556_c2e9_4dac_9a8c_dbe05a33f57a : FloatBinding
	{
		private FrogCharacterController CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (FrogCharacterController)UnityComponent;
		}
		public override string CoherenceComponentName => "Character_FrogCharacterController_4441217298144173242";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.attackCooldownBoost);
			set => CastedUnityComponent.attackCooldownBoost = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Character_FrogCharacterController_4441217298144173242)coherenceComponent).attackCooldownBoost;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Character_FrogCharacterController_4441217298144173242)coherenceComponent;
			update.attackCooldownBoost = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Character_FrogCharacterController_4441217298144173242();
		}
	}

	public class Binding_ef7ce5f54c7d78b479854b7248d15c5a_9d147bda_91ab_471b_b7c6_5a3e1109f5a7 : FloatBinding
	{
		private FrogCharacterController CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (FrogCharacterController)UnityComponent;
		}
		public override string CoherenceComponentName => "Character_FrogCharacterController_4441217298144173242";

		public override uint FieldMask => 0b00000000000000000000000000000100;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.attackRangeBoost);
			set => CastedUnityComponent.attackRangeBoost = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Character_FrogCharacterController_4441217298144173242)coherenceComponent).attackRangeBoost;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Character_FrogCharacterController_4441217298144173242)coherenceComponent;
			update.attackRangeBoost = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Character_FrogCharacterController_4441217298144173242();
		}
	}

	public class Binding_ef7ce5f54c7d78b479854b7248d15c5a_906ab406_4ac3_4433_98db_2b8e552c92ce : FloatBinding
	{
		private FrogCharacterController CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (FrogCharacterController)UnityComponent;
		}
		public override string CoherenceComponentName => "Character_FrogCharacterController_4441217298144173242";

		public override uint FieldMask => 0b00000000000000000000000000001000;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.attackSizeBoost);
			set => CastedUnityComponent.attackSizeBoost = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Character_FrogCharacterController_4441217298144173242)coherenceComponent).attackSizeBoost;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Character_FrogCharacterController_4441217298144173242)coherenceComponent;
			update.attackSizeBoost = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Character_FrogCharacterController_4441217298144173242();
		}
	}

	public class Binding_ef7ce5f54c7d78b479854b7248d15c5a_bea714cc_23b7_4b83_9f65_df6f5260da97 : FloatBinding
	{
		private FrogCharacterController CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (FrogCharacterController)UnityComponent;
		}
		public override string CoherenceComponentName => "Character_FrogCharacterController_4441217298144173242";

		public override uint FieldMask => 0b00000000000000000000000000010000;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.attackSpeedBoost);
			set => CastedUnityComponent.attackSpeedBoost = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Character_FrogCharacterController_4441217298144173242)coherenceComponent).attackSpeedBoost;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Character_FrogCharacterController_4441217298144173242)coherenceComponent;
			update.attackSpeedBoost = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Character_FrogCharacterController_4441217298144173242();
		}
	}

	public class Binding_ef7ce5f54c7d78b479854b7248d15c5a_ca57d5ce_8193_4991_a773_3a0e65b5c4af : FloatBinding
	{
		private FrogCharacterController CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (FrogCharacterController)UnityComponent;
		}
		public override string CoherenceComponentName => "Character_FrogCharacterController_4441217298144173242";

		public override uint FieldMask => 0b00000000000000000000000000100000;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.attackDurationBoost);
			set => CastedUnityComponent.attackDurationBoost = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Character_FrogCharacterController_4441217298144173242)coherenceComponent).attackDurationBoost;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Character_FrogCharacterController_4441217298144173242)coherenceComponent;
			update.attackDurationBoost = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Character_FrogCharacterController_4441217298144173242();
		}
	}

	public class Binding_ef7ce5f54c7d78b479854b7248d15c5a_064e68fa_24e7_4b17_8fa2_f0b119d1323b : FloatBinding
	{
		private FrogCharacterController CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (FrogCharacterController)UnityComponent;
		}
		public override string CoherenceComponentName => "Character_FrogCharacterController_4441217298144173242";

		public override uint FieldMask => 0b00000000000000000000000001000000;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.attackSpecialStrengthBoost);
			set => CastedUnityComponent.attackSpecialStrengthBoost = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Character_FrogCharacterController_4441217298144173242)coherenceComponent).attackSpecialStrengthBoost;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Character_FrogCharacterController_4441217298144173242)coherenceComponent;
			update.attackSpecialStrengthBoost = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Character_FrogCharacterController_4441217298144173242();
		}
	}

	public class Binding_ef7ce5f54c7d78b479854b7248d15c5a_80d3d67f_178c_4fac_8085_ecf3522085ad : FloatBinding
	{
		private FrogCharacterController CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (FrogCharacterController)UnityComponent;
		}
		public override string CoherenceComponentName => "Character_FrogCharacterController_4441217298144173242";

		public override uint FieldMask => 0b00000000000000000000000010000000;

		public override float Value
		{
			get => (float)(System.Single)(CastedUnityComponent.attackSpecialDurationBoost);
			set => CastedUnityComponent.attackSpecialDurationBoost = (System.Single)(value);
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Character_FrogCharacterController_4441217298144173242)coherenceComponent).attackSpecialDurationBoost;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Character_FrogCharacterController_4441217298144173242)coherenceComponent;
			update.attackSpecialDurationBoost = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Character_FrogCharacterController_4441217298144173242();
		}
	}

	public class Binding_ef7ce5f54c7d78b479854b7248d15c5a_ac30f734_33cc_40a3_a886_b592a3046d43 : IntAnimatorParameterBinding
	{
		private UnityEngine.Animator CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Animator)UnityComponent;
		}
		public override string CoherenceComponentName => "Character_UnityEngine__char_46_Animator_4441217298144173237";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override int Value
		{
			get => (int)(CastedUnityComponent.GetInteger(CastedDescriptor.ParameterHash));
			set => CastedUnityComponent.SetInteger(CastedDescriptor.ParameterHash, (value));
		}

		protected override int ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Character_UnityEngine__char_46_Animator_4441217298144173237)coherenceComponent).character;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Character_UnityEngine__char_46_Animator_4441217298144173237)coherenceComponent;
			update.character = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Character_UnityEngine__char_46_Animator_4441217298144173237();
		}
	}

	public class Binding_ef7ce5f54c7d78b479854b7248d15c5a_8c6cd158_e10c_44c9_bc64_2dba00feb83c : FloatAnimatorParameterBinding
	{
		private UnityEngine.Animator CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Animator)UnityComponent;
		}
		public override string CoherenceComponentName => "Character_UnityEngine__char_46_Animator_4441217298144173237";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override float Value
		{
			get => (float)(CastedUnityComponent.GetFloat(CastedDescriptor.ParameterHash));
			set => CastedUnityComponent.SetFloat(CastedDescriptor.ParameterHash, (value));
		}

		protected override float ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Character_UnityEngine__char_46_Animator_4441217298144173237)coherenceComponent).Speed;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Character_UnityEngine__char_46_Animator_4441217298144173237)coherenceComponent;
			update.Speed = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Character_UnityEngine__char_46_Animator_4441217298144173237();
		}
	}

	public class Binding_ef7ce5f54c7d78b479854b7248d15c5a_4b0cd8bc_f60f_4023_8a83_ac0fb844711e : DeepPositionBinding
	{
		private UnityEngine.Transform CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "Character_UnityEngine__char_46_Transform_4441217299098064662";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(CastedUnityComponent.localPosition);
			set => CastedUnityComponent.localPosition = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Character_UnityEngine__char_46_Transform_4441217299098064662)coherenceComponent).position;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Character_UnityEngine__char_46_Transform_4441217299098064662)coherenceComponent;
			update.position = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Character_UnityEngine__char_46_Transform_4441217299098064662();
		}
	}

	public class Binding_ef7ce5f54c7d78b479854b7248d15c5a_4a028cf7_a4a1_4371_8612_5fe40171177c : DeepRotationBinding
	{
		private UnityEngine.Transform CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "Character_UnityEngine__char_46_Transform_4441217299098064662";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override Quaternion Value
		{
			get => (Quaternion)(UnityEngine.Quaternion)(CastedUnityComponent.localRotation);
			set => CastedUnityComponent.localRotation = (UnityEngine.Quaternion)(value);
		}

		protected override Quaternion ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
		{
			var value = ((Character_UnityEngine__char_46_Transform_4441217299098064662)coherenceComponent).rotation;
			return value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Character_UnityEngine__char_46_Transform_4441217299098064662)coherenceComponent;
			update.rotation = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Character_UnityEngine__char_46_Transform_4441217299098064662();
		}
	}


	[Preserve]
	[AddComponentMenu("coherence/Baked/Baked 'Character' (auto assigned)")]
	[RequireComponent(typeof(CoherenceSync))]
	public class CoherenceSyncCharacter : CoherenceSyncBaked
	{
		private CoherenceSync coherenceSync;
		private Logger logger;

		// Cached targets for commands

		private IClient client;
		private CoherenceMonoBridge monoBridge => coherenceSync.MonoBridge;

		protected void Awake()
		{
			coherenceSync = GetComponent<CoherenceSync>();
			coherenceSync.usingReflection = false;

			logger = coherenceSync.logger.With<CoherenceSyncCharacter>();
			if (coherenceSync.TryGetBindingByGuid("b5eae117-ad0b-4dbb-af1c-17c36e143c31", "position", out Binding InternalWorldPosition_Translation_value))
			{
				var clone = new Binding_ef7ce5f54c7d78b479854b7248d15c5a_b5eae117_ad0b_4dbb_af1c_17c36e143c31();
				InternalWorldPosition_Translation_value.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalWorldPosition_Translation_value)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).position");
			}
			if (coherenceSync.TryGetBindingByGuid("4b2dbcaa-589a-4ed2-a802-76d495bf93e2", "rotation", out Binding InternalWorldOrientation_Rotation_value))
			{
				var clone = new Binding_ef7ce5f54c7d78b479854b7248d15c5a_4b2dbcaa_589a_4ed2_a802_76d495bf93e2();
				InternalWorldOrientation_Rotation_value.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalWorldOrientation_Rotation_value)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).rotation");
			}
			if (coherenceSync.TryGetBindingByGuid("779b4dd7-cf60-436e-a4e9-1bcbe3f5fbab", "weaponStartPoint", out Binding InternalCharacter_FrogCharacterController_4441217298144173242_Character_FrogCharacterController_4441217298144173242_weaponStartPoint))
			{
				var clone = new Binding_ef7ce5f54c7d78b479854b7248d15c5a_779b4dd7_cf60_436e_a4e9_1bcbe3f5fbab();
				InternalCharacter_FrogCharacterController_4441217298144173242_Character_FrogCharacterController_4441217298144173242_weaponStartPoint.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalCharacter_FrogCharacterController_4441217298144173242_Character_FrogCharacterController_4441217298144173242_weaponStartPoint)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (FrogCharacterController).weaponStartPoint");
			}
			if (coherenceSync.TryGetBindingByGuid("c48e1556-c2e9-4dac-9a8c-dbe05a33f57a", "attackCooldownBoost", out Binding InternalCharacter_FrogCharacterController_4441217298144173242_Character_FrogCharacterController_4441217298144173242_attackCooldownBoost))
			{
				var clone = new Binding_ef7ce5f54c7d78b479854b7248d15c5a_c48e1556_c2e9_4dac_9a8c_dbe05a33f57a();
				InternalCharacter_FrogCharacterController_4441217298144173242_Character_FrogCharacterController_4441217298144173242_attackCooldownBoost.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalCharacter_FrogCharacterController_4441217298144173242_Character_FrogCharacterController_4441217298144173242_attackCooldownBoost)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (FrogCharacterController).attackCooldownBoost");
			}
			if (coherenceSync.TryGetBindingByGuid("9d147bda-91ab-471b-b7c6-5a3e1109f5a7", "attackRangeBoost", out Binding InternalCharacter_FrogCharacterController_4441217298144173242_Character_FrogCharacterController_4441217298144173242_attackRangeBoost))
			{
				var clone = new Binding_ef7ce5f54c7d78b479854b7248d15c5a_9d147bda_91ab_471b_b7c6_5a3e1109f5a7();
				InternalCharacter_FrogCharacterController_4441217298144173242_Character_FrogCharacterController_4441217298144173242_attackRangeBoost.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalCharacter_FrogCharacterController_4441217298144173242_Character_FrogCharacterController_4441217298144173242_attackRangeBoost)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (FrogCharacterController).attackRangeBoost");
			}
			if (coherenceSync.TryGetBindingByGuid("906ab406-4ac3-4433-98db-2b8e552c92ce", "attackSizeBoost", out Binding InternalCharacter_FrogCharacterController_4441217298144173242_Character_FrogCharacterController_4441217298144173242_attackSizeBoost))
			{
				var clone = new Binding_ef7ce5f54c7d78b479854b7248d15c5a_906ab406_4ac3_4433_98db_2b8e552c92ce();
				InternalCharacter_FrogCharacterController_4441217298144173242_Character_FrogCharacterController_4441217298144173242_attackSizeBoost.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalCharacter_FrogCharacterController_4441217298144173242_Character_FrogCharacterController_4441217298144173242_attackSizeBoost)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (FrogCharacterController).attackSizeBoost");
			}
			if (coherenceSync.TryGetBindingByGuid("bea714cc-23b7-4b83-9f65-df6f5260da97", "attackSpeedBoost", out Binding InternalCharacter_FrogCharacterController_4441217298144173242_Character_FrogCharacterController_4441217298144173242_attackSpeedBoost))
			{
				var clone = new Binding_ef7ce5f54c7d78b479854b7248d15c5a_bea714cc_23b7_4b83_9f65_df6f5260da97();
				InternalCharacter_FrogCharacterController_4441217298144173242_Character_FrogCharacterController_4441217298144173242_attackSpeedBoost.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalCharacter_FrogCharacterController_4441217298144173242_Character_FrogCharacterController_4441217298144173242_attackSpeedBoost)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (FrogCharacterController).attackSpeedBoost");
			}
			if (coherenceSync.TryGetBindingByGuid("ca57d5ce-8193-4991-a773-3a0e65b5c4af", "attackDurationBoost", out Binding InternalCharacter_FrogCharacterController_4441217298144173242_Character_FrogCharacterController_4441217298144173242_attackDurationBoost))
			{
				var clone = new Binding_ef7ce5f54c7d78b479854b7248d15c5a_ca57d5ce_8193_4991_a773_3a0e65b5c4af();
				InternalCharacter_FrogCharacterController_4441217298144173242_Character_FrogCharacterController_4441217298144173242_attackDurationBoost.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalCharacter_FrogCharacterController_4441217298144173242_Character_FrogCharacterController_4441217298144173242_attackDurationBoost)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (FrogCharacterController).attackDurationBoost");
			}
			if (coherenceSync.TryGetBindingByGuid("064e68fa-24e7-4b17-8fa2-f0b119d1323b", "attackSpecialStrengthBoost", out Binding InternalCharacter_FrogCharacterController_4441217298144173242_Character_FrogCharacterController_4441217298144173242_attackSpecialStrengthBoost))
			{
				var clone = new Binding_ef7ce5f54c7d78b479854b7248d15c5a_064e68fa_24e7_4b17_8fa2_f0b119d1323b();
				InternalCharacter_FrogCharacterController_4441217298144173242_Character_FrogCharacterController_4441217298144173242_attackSpecialStrengthBoost.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalCharacter_FrogCharacterController_4441217298144173242_Character_FrogCharacterController_4441217298144173242_attackSpecialStrengthBoost)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (FrogCharacterController).attackSpecialStrengthBoost");
			}
			if (coherenceSync.TryGetBindingByGuid("80d3d67f-178c-4fac-8085-ecf3522085ad", "attackSpecialDurationBoost", out Binding InternalCharacter_FrogCharacterController_4441217298144173242_Character_FrogCharacterController_4441217298144173242_attackSpecialDurationBoost))
			{
				var clone = new Binding_ef7ce5f54c7d78b479854b7248d15c5a_80d3d67f_178c_4fac_8085_ecf3522085ad();
				InternalCharacter_FrogCharacterController_4441217298144173242_Character_FrogCharacterController_4441217298144173242_attackSpecialDurationBoost.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalCharacter_FrogCharacterController_4441217298144173242_Character_FrogCharacterController_4441217298144173242_attackSpecialDurationBoost)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (FrogCharacterController).attackSpecialDurationBoost");
			}
			if (coherenceSync.TryGetBindingByGuid("ac30f734-33cc-40a3-a886-b592a3046d43", "character", out Binding InternalCharacter_UnityEngine__char_46_Animator_4441217298144173237_Character_UnityEngine__char_46_Animator_4441217298144173237_character))
			{
				var clone = new Binding_ef7ce5f54c7d78b479854b7248d15c5a_ac30f734_33cc_40a3_a886_b592a3046d43();
				InternalCharacter_UnityEngine__char_46_Animator_4441217298144173237_Character_UnityEngine__char_46_Animator_4441217298144173237_character.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalCharacter_UnityEngine__char_46_Animator_4441217298144173237_Character_UnityEngine__char_46_Animator_4441217298144173237_character)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Animator).character");
			}
			if (coherenceSync.TryGetBindingByGuid("8c6cd158-e10c-44c9-bc64-2dba00feb83c", "Speed", out Binding InternalCharacter_UnityEngine__char_46_Animator_4441217298144173237_Character_UnityEngine__char_46_Animator_4441217298144173237_Speed))
			{
				var clone = new Binding_ef7ce5f54c7d78b479854b7248d15c5a_8c6cd158_e10c_44c9_bc64_2dba00feb83c();
				InternalCharacter_UnityEngine__char_46_Animator_4441217298144173237_Character_UnityEngine__char_46_Animator_4441217298144173237_Speed.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalCharacter_UnityEngine__char_46_Animator_4441217298144173237_Character_UnityEngine__char_46_Animator_4441217298144173237_Speed)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Animator).Speed");
			}
			if (coherenceSync.TryGetBindingByGuid("4b0cd8bc-f60f-4023-8a83-ac0fb844711e", "position", out Binding InternalCharacter_UnityEngine__char_46_Transform_4441217299098064662_Character_UnityEngine__char_46_Transform_4441217299098064662_position))
			{
				var clone = new Binding_ef7ce5f54c7d78b479854b7248d15c5a_4b0cd8bc_f60f_4023_8a83_ac0fb844711e();
				InternalCharacter_UnityEngine__char_46_Transform_4441217299098064662_Character_UnityEngine__char_46_Transform_4441217299098064662_position.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalCharacter_UnityEngine__char_46_Transform_4441217299098064662_Character_UnityEngine__char_46_Transform_4441217299098064662_position)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).position");
			}
			if (coherenceSync.TryGetBindingByGuid("4a028cf7-a4a1-4371-8612-5fe40171177c", "rotation", out Binding InternalCharacter_UnityEngine__char_46_Transform_4441217299098064662_Character_UnityEngine__char_46_Transform_4441217299098064662_rotation))
			{
				var clone = new Binding_ef7ce5f54c7d78b479854b7248d15c5a_4a028cf7_a4a1_4371_8612_5fe40171177c();
				InternalCharacter_UnityEngine__char_46_Transform_4441217299098064662_Character_UnityEngine__char_46_Transform_4441217299098064662_rotation.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalCharacter_UnityEngine__char_46_Transform_4441217299098064662_Character_UnityEngine__char_46_Transform_4441217299098064662_rotation)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).rotation");
			}
		}

		public override List<ICoherenceComponentData> CreateEntity()
		{
			if (coherenceSync.UsesLODsAtRuntime && (Archetypes.IndexForName.TryGetValue(coherenceSync.Archetype.ArchetypeName, out int archetypeIndex)))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
			else
			{
				logger.Warning($"Unable to find archetype {coherenceSync.Archetype.ArchetypeName} in dictionary. Please, bake manually (coherence > Bake)");
			}

			return null;
		}

		public override void Initialize(CoherenceSync sync, IClient client)
		{
			if (coherenceSync == null)
			{
				coherenceSync = sync;
			}
			this.client = client;
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				default:
					logger.Warning($"[CoherenceSyncCharacter] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
