// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.SimulationFrame;
	using Coherence.Entity;
	using Coherence.Utils;
	using Coherence.Brook;
	using Coherence.Toolkit;
	using UnityEngine;

	public struct Map_MapBehaviour_3964490343674139607 : ICoherenceComponentData
	{
		public bool enabled;
		public float minDistanceWithPlayer;
		public SerializeEntityID mapTilesParent;

		public override string ToString()
		{
			return $"Map_MapBehaviour_3964490343674139607(enabled: {enabled}, minDistanceWithPlayer: {minDistanceWithPlayer}, mapTilesParent: {mapTilesParent})";
		}

		public uint GetComponentType() => Definition.InternalMap_MapBehaviour_3964490343674139607;

		public const int order = 0;

		public int GetComponentOrder() => order;

		public AbsoluteSimulationFrame Frame;
	

		public void SetSimulationFrame(AbsoluteSimulationFrame frame)
		{
			Frame = frame;
		}

		public AbsoluteSimulationFrame GetSimulationFrame() => Frame;

		public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
		{
			var other = (Map_MapBehaviour_3964490343674139607)data;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				enabled = other.enabled;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				minDistanceWithPlayer = other.minDistanceWithPlayer;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				mapTilesParent = other.mapTilesParent;
			}
			mask >>= 1;
			return this;
		}

		public uint DiffWith(ICoherenceComponentData data)
		{
			throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");

		}

		public static void Serialize(Map_MapBehaviour_3964490343674139607 data, uint mask, IOutProtocolBitStream bitStream)
		{
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteBool(data.enabled);
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteFloat(data.minDistanceWithPlayer, FloatMeta.NoCompression());
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteEntity(data.mapTilesParent);
			}
			mask >>= 1;
		}

		public static (Map_MapBehaviour_3964490343674139607, uint, uint?) Deserialize(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new Map_MapBehaviour_3964490343674139607();
	
			if (bitStream.ReadMask())
			{
				val.enabled = bitStream.ReadBool();
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.minDistanceWithPlayer = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000010;
			}
			if (bitStream.ReadMask())
			{
				val.mapTilesParent = bitStream.ReadEntity();
				mask |= 0b00000000000000000000000000000100;
			}
			return (val, mask, null);
		}
		public static (Map_MapBehaviour_3964490343674139607, uint, uint?) DeserializeArchetypeMap_47cb5312f9d22b34095ab0d72bfecbcd_Map_MapBehaviour_3964490343674139607_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new Map_MapBehaviour_3964490343674139607();
			if (bitStream.ReadMask())
			{
				val.enabled = bitStream.ReadBool();
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.minDistanceWithPlayer = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000010;
			}
			if (bitStream.ReadMask())
			{
				val.mapTilesParent = bitStream.ReadEntity();
				mask |= 0b00000000000000000000000000000100;
			}

			return (val, mask, 0);
		}

		/// <summary>
		/// Resets byte array references to the local array instance that is kept in the lastSentData.
		/// If the array content has changed but remains of same length, the new content is copied into the local array instance.
		/// If the array length has changed, the array is cloned and overwrites the local instance.
		/// If the array has not changed, the reference is reset to the local array instance.
		/// Otherwise, changes to other fields on the component might cause the local array instance reference to become permanently lost.
		/// </summary>
		public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
		{
			var last = lastSent as Map_MapBehaviour_3964490343674139607?;
	
		}
	}
}