// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Map_MapBehaviour__char_46_ClearMap_2dc0b920_65b2_4e81_a553_c89faf48edd2 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalMap_MapBehaviour__char_46_ClearMap_2dc0b920_65b2_4e81_a553_c89faf48edd2;

		public static void Serialize(Map_MapBehaviour__char_46_ClearMap_2dc0b920_65b2_4e81_a553_c89faf48edd2 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Map_MapBehaviour__char_46_ClearMap_2dc0b920_65b2_4e81_a553_c89faf48edd2 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Map_MapBehaviour__char_46_ClearMap_2dc0b920_65b2_4e81_a553_c89faf48edd2
			(
			){};
		}
	}
}
