// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Map_MapBehaviour__char_46_GenerateNewTilesAroundPosition_fa461b82_7652_4711_a787_f1c1055bbbc2 : IEntityCommand
	{
		public Vector2 position;

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalMap_MapBehaviour__char_46_GenerateNewTilesAroundPosition_fa461b82_7652_4711_a787_f1c1055bbbc2;

		public Map_MapBehaviour__char_46_GenerateNewTilesAroundPosition_fa461b82_7652_4711_a787_f1c1055bbbc2
		(
			Vector2 dataposition
		)
		{
			position = dataposition;
		}

		public static void Serialize(Map_MapBehaviour__char_46_GenerateNewTilesAroundPosition_fa461b82_7652_4711_a787_f1c1055bbbc2 commandData, IOutProtocolBitStream bitStream)
		{
			var converted_position = commandData.position.ToCoreVector2();
			bitStream.WriteVector2(converted_position, FloatMeta.NoCompression());
		}

		public static Map_MapBehaviour__char_46_GenerateNewTilesAroundPosition_fa461b82_7652_4711_a787_f1c1055bbbc2 Deserialize(IInProtocolBitStream bitStream)
		{
			var converted_position = bitStream.ReadVector2(FloatMeta.NoCompression());
			var dataposition = converted_position.ToUnityVector2();

			return new Map_MapBehaviour__char_46_GenerateNewTilesAroundPosition_fa461b82_7652_4711_a787_f1c1055bbbc2
			(
				dataposition
			){};
		}
	}
}
